Repository DisnakeDev/disnake, pull requests merged in 2021-11, with the labels that each got.

#100 Add attachment descriptions
  disnake/file.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/types/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: enhancement

#109 Add 'on_raw_member_screening_reject' event, rename previous event
  disnake/flags.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/raw_models.py
  docs/api.rst
Labels: enhancement

#113 Update docs favicon
  docs/conf.py
  docs/images/discord_py_logo.ico
  docs/images/disnake_logo.ico
Labels: documentation

#116 Fix documentation warnings.
  disnake/interactions/application_command.py
  docs/api.rst
  docs/whats_new.rst
Labels: documentation

#118 Improve warnings, fix `DeprecationWarning` filters
  disnake/__init__.py
  disnake/app_commands.py
  disnake/custom_warnings.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/utils.py
  docs/api.rst
Labels: bugfix

#121 Add `InteractionBot` and `AutoShardedInteractionBot` documentation.
  disnake/ext/commands/interaction_bot_base.py
  docs/ext/commands/api.rst
Labels: documentation

#136 Fixed `from_dict` in app commands
  disnake/app_commands.py
  disnake/utils.py
Labels: bug, p: high, s: needs review

#115 Add links to source code in docs
  docs/_static/style.css
  docs/conf.py
Labels: documentation, p: low, s: needs review

#135 Version v2.2.2
  README.ja.rst
  README.rst
  disnake/__init__.py
  disnake/app_commands.py
  disnake/audit_logs.py
  disnake/embeds.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/http.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/ui/select.py
  disnake/utils.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  docs/_static/style.css
  docs/_templates/layout.html
  docs/api.rst
  docs/conf.py
  docs/ext/commands/api.rst
  docs/faq.rst
  docs/locale/ja/LC_MESSAGES/faq.po
  docs/whats_new.rst
  setup.py
Labels: s: needs review

#140 Fixed possibly misunderstand in `Interaction.original_message` documentation.
  disnake/interactions/base.py
Labels: documentation, p: low

#145 Fixed wrong PartyType.checkers ID.
  disnake/enums.py
Labels: bug

#139 Add approximate member/presence count to guilds
  disnake/guild.py
  disnake/http.py
  disnake/types/guild.py
Labels: api support, s: needs review

#148 Update enums, flags, guild features
  disnake/enums.py
  disnake/flags.py
  disnake/guild.py
  disnake/message.py
  disnake/types/guild.py
  docs/api.rst
Labels: enhancement, p: low, s: needs review

#143 Fix example annotations
  examples/background_task.py
  examples/background_task_asyncio.py
  examples/basic_voice.py
  examples/converters.py
  examples/reaction_roles.py
  examples/views/disable_view.py
Labels: documentation, s: needs review

#156 Fix broken import in invite types
  disnake/types/invite.py
Labels: bug, s: needs review

#151 Support scheduled events
  disnake/__init__.py
  disnake/abc.py
  disnake/audit_logs.py
  disnake/client.py
  disnake/enums.py
  disnake/flags.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/http.py
  disnake/invite.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/invite.py
  disnake/utils.py
  docs/api.rst
  tests/cogs/events.py
Labels: enhancement, api support, p: medium, s: in progress

#132 Support setting slowmode on thread creation
  disnake/channel.py
  disnake/guild.py
  disnake/http.py
  disnake/message.py
  disnake/threads.py
Labels: enhancement, api support, p: low, s: needs review

#152 Replace favicon and banner.
  assets/banner.png
  docs/images/disnake_logo.ico
Labels: documentation, s: needs review

#130 refactor slash commands
  README.rst
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/interactions/application_command.py
  docs/ext/commands/api.rst
  docs/ext/commands/slash_commands.rst
  examples/slash_commands/autocomplete.py
  examples/slash_commands/converters.py
  examples/slash_commands/injections.py
  examples/slash_commands/param.py
  examples/slash_commands/subcmd.py
  tests/cogs/injections.py
  tests/cogs/slash_commands.py
Labels: enhancement, breaking change, p: medium, s: needs review

#166 Fix injections link to commit in docs
  docs/ext/commands/slash_commands.rst
Labels: documentation

#172 Update JP readme to match the English one
  README.ja.rst
Labels: documentation

#162 Add support for Text in Voice Channels
  .gitignore
  disnake/abc.py
  disnake/channel.py
  disnake/ext/commands/context.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/state.py
  disnake/webhook/async_.py
Labels: enhancement, api support, s: blocked
