Repository DisnakeDev/disnake, pull requests merged in 2021-12, with the labels that each got.

#153 Updated the documentation.
  disnake/asset.py
  disnake/channel.py
  disnake/client.py
  disnake/emoji.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/guild.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/member.py
  disnake/message.py
  disnake/partial_emoji.py
  disnake/reaction.py
  disnake/role.py
  disnake/shard.py
  disnake/threads.py
  disnake/ui/view.py
  disnake/webhook/async_.py
  docs/_static/custom.js
  docs/api.rst
  docs/discord.rst
  docs/ext/commands/api.rst
  docs/images/discord_add_to_server.png
  docs/images/discord_bot_tab.png
  docs/images/discord_bot_user_options.png
  docs/images/discord_create_app_button.png
  docs/images/discord_create_app_form.png
  docs/images/discord_create_bot_user.png
  docs/images/discord_general_authorization_link.png
  docs/images/discord_general_scope.png
  docs/images/discord_oauth2.png
  docs/images/discord_oauth2_perms.png
  docs/images/discord_oauth2_scope.png
  docs/images/discord_url_generator.png
  docs/images/discord_url_generator_scopes.png
  docs/intro.rst
  docs/whats_new.rst
  setup.py
Labels: documentation, s: needs review

#160 Add `start_embedded_activities` permission
  disnake/permissions.py
Labels: enhancement, api support, p: low, s: needs review

#183 Deleted invalid PartyType ID.
  disnake/enums.py
Labels: bug

#163 Fix button/select decorator return types
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
Labels: bug, p: low, s: needs review

#165 Deleted unused imports.
  disnake/abc.py
  disnake/channel.py
  disnake/embeds.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/context.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/help.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/flags.py
  disnake/http.py
  disnake/integrations.py
  disnake/member.py
  disnake/message.py
  disnake/role.py
  disnake/template.py
  disnake/ui/select.py
  disnake/webhook/sync.py
  disnake/widget.py
Labels: p: low, s: needs review

#176 Fix dispatch of typing events in DMs
  disnake/channel.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/raw_models.py
  docs/api.rst
Labels: bug, s: needs review

#184 Replace `json.loads` with `utils._from_json`
  disnake/player.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: enhancement, p: low, s: needs review

#188 Clarify `Interaction.send` docs
  disnake/interactions/base.py
Labels: documentation, p: low, s: needs review

#177 Text in Voice: new VoiceChannel attributes
  disnake/channel.py
  disnake/message.py
  disnake/state.py
  disnake/types/channel.py
  docs/api.rst
Labels: enhancement, api support, s: needs review

#191 Rewrite `README` - with new styling and shortened descriptions.
  README.ja.rst
  README.md
  README.rst
Labels: documentation, s: needs review, meta / refactor

#182 Try to get object from cache first.
  disnake/interactions/application_command.py
  disnake/interactions/base.py
Labels: bug, p: medium, s: needs review

#187 Add `ThreadArchiveDuration` enum
  disnake/channel.py
  disnake/enums.py
  disnake/http.py
  disnake/message.py
  disnake/threads.py
  disnake/types/channel.py
  disnake/types/threads.py
  docs/api.rst
Labels: enhancement, s: needs review

#193 Fix images not showing in embed when using `Interaction.edit_original_message`.
  disnake/webhook/async_.py
Labels: bug

#200 Update version guarantees in docs
  README.md
  docs/version_guarantees.rst
Labels: documentation, s: needs review

#207 fix disnake banner does not display banner in PyPI
  README.md
Labels: meta / refactor

#197 Fix `Message.channel` is `DMChannel` in `on_message` in some cases.
  disnake/state.py
Labels: bug, p: medium, s: needs review

#124 Always close files after requests
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: bug, p: low

#205 Fixed a small command synchronization bug
  disnake/ext/commands/interaction_bot_base.py
  docs/ext/commands/additional_info.rst
  docs/ext/commands/index.rst
Labels: bug, p: medium, s: needs review

#199 Add `fail_if_not_exists` to `Message.reply()`
  disnake/message.py
Labels: enhancement, s: needs review

#161 Add support for guild time outs.
  disnake/audit_logs.py
  disnake/embeds.py
  disnake/guild.py
  disnake/member.py
  disnake/permissions.py
  disnake/types/audit_log.py
  docs/api.rst
Labels: enhancement, api support, s: in progress

#164 Adding Support For Newer Aiohttp Versions
  requirements.txt
Labels: p: low, s: blocked, dependencies

#214 Fix a few issues in the docs of new features
  disnake/ext/commands/params.py
  disnake/interactions/application_command.py
  disnake/invite.py
  disnake/message.py
  docs/api.rst
Labels: documentation, s: needs review

#217 Add support for reason in scheduled events.
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/http.py
Labels: api support, s: needs review

#219 Fix error with `Guild.timeout()`
  disnake/guild.py
  disnake/member.py
Labels: bug, s: needs review

#221 Support for datetime and renamed `guild_timeout`, `seconds`.
  disnake/audit_logs.py
  disnake/guild.py
  disnake/member.py
  docs/api.rst
Labels: enhancement, s: in progress

#222 Remove `on_member_screening_reject` event
  disnake/flags.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/raw_models.py
  docs/api.rst
Labels: bug, s: needs review

#223 Improve timeout method parameters
  disnake/guild.py
  disnake/member.py
Labels: enhancement, s: needs review

#215 Add audit log target converter for scheduled events
  disnake/audit_logs.py
Labels: bug, s: needs review

#210 Add use Korean to slash_command()
  disnake/app_commands.py
Labels: bug

#204 Add changelog for v2.3.0
  disnake/ext/commands/converter.py
  docs/conf.py
  docs/ext/commands/api.rst
  docs/whats_new.rst
Labels: documentation, s: needs review

#225 Add `locale` and `guild_locale` properties to interactions.
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/types/interactions.py
Labels: api support, s: needs review

#169 Add `isort` and `black` pre-commit hooks.
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  requirements_dev.txt
Labels: s: needs review, meta / refactor

#231 python 3.10 union type alias fix
  disnake/ext/commands/params.py
Labels: bug, p: medium, s: needs review

#232 Rename `tests` directory
  test_bot/__init__.py
  test_bot/cogs/events.py
  test_bot/cogs/injections.py
  test_bot/cogs/message_commands.py
  test_bot/cogs/slash_commands.py
  test_bot/cogs/user_commands.py
  test_bot/main.py
  test_launcher.py
Labels: s: needs review, meta / refactor

#224 Added lower level components syntax
  disnake/abc.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/ui/__init__.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
  disnake/ui/view.py
  disnake/webhook/async_.py
  docs/api.rst
  docs/conf.py
Labels: enhancement, s: in progress

#235 Fix missing dropdown icon in docs
  docs/_static/style.css
  docs/conf.py
  docs/extensions/builder.py
Labels: bug, documentation, s: needs review

#238 feat(MessageFlags): Add `failed_to_mention_roles_in_thread` flag (1 << 8).
  disnake/flags.py
Labels: api support, s: needs review

#230 Use logger for application command sync debug
  disnake/client.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/interaction_bot_base.py
  docs/ext/commands/slash_commands.rst
Labels: enhancement, s: needs review

#240 Minor refactoring of the sync algo
  disnake/ext/commands/interaction_bot_base.py
Labels: enhancement, s: needs review

#236 Show tooltips when hovering over links in docs
  docs/_static/style.css
  docs/conf.py
  setup.py
Labels: documentation, enhancement, s: needs review

#209 Handle button disabling in `paginator.py` example.
  examples/views/button/paginator.py
Labels: documentation
