Repository DisnakeDev/disnake, pull requests merged in 2022-03, with the labels that each got.

#345 chore: update dev dependencies
  .pre-commit-config.yaml
  disnake/backoff.py
  disnake/flags.py
  disnake/utils.py
  requirements_dev.txt
  test_bot/cogs/injections.py
Labels: s: needs review, dependencies

#381 fix: missing/incorrect slots
  .github/workflows/lint.yml
  disnake/activity.py
  disnake/asset.py
  disnake/emoji.py
  disnake/partial_emoji.py
  disnake/sticker.py
  disnake/widget.py
  pyproject.toml
  requirements_dev.txt
Labels: bug, s: needs review, meta

#287 chore: support public stages being deprecated
  disnake/channel.py
  disnake/stage_instance.py
  docs/api.rst
Labels: enhancement, s: needs review

#386 build: update ci, fix tasks
  .github/workflows/lint.yml
  pyproject.toml
Labels: s: needs review, meta

#376 feat: add scheduled event converter
  disnake/ext/commands/converter.py
  disnake/ext/commands/errors.py
  docs/ext/commands/api.rst
  docs/ext/commands/commands.rst
Labels: enhancement, s: needs review

#358 feat: implement Guild.search_members
  disnake/guild.py
  disnake/http.py
Labels: api support, s: needs review

#326 feat: add support for list/dict in Select option kwarg
  disnake/ui/select.py
Labels: enhancement, s: needs review

#387 refactor: enable additional pyright rules
  disnake/__init__.py
  disnake/abc.py
  disnake/audit_logs.py
  disnake/backoff.py
  disnake/channel.py
  disnake/client.py
  disnake/components.py
  disnake/enums.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/help.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/guild.py
  disnake/http.py
  disnake/interactions/application_command.py
  disnake/invite.py
  disnake/iterators.py
  disnake/opus.py
  disnake/player.py
  disnake/shard.py
  disnake/state.py
  disnake/types/interactions.py
  disnake/types/invite.py
  disnake/ui/action_row.py
  disnake/ui/item.py
  disnake/ui/select.py
  disnake/ui/view.py
  disnake/utils.py
  disnake/voice_client.py
  docs/extensions/attributetable.py
  docs/extensions/exception_hierarchy.py
  pyproject.toml
  requirements_dev.txt
  test_bot/cogs/events.py
  test_bot/cogs/injections.py
  test_bot/cogs/slash_commands.py
  test_launcher.py
Labels: bug, s: needs review, refactor/typing

#388 minor: raise error in search_members if limit is below 1
  disnake/guild.py
Labels: enhancement, p: low, s: needs review

#374 docs: add interaction annotation types, update voice regions
  disnake/interactions/application_command.py
  docs/api.rst
Labels: documentation, s: needs review

#383 fix PartialInviteChannel.__str__
  disnake/invite.py
  disnake/types/channel.py
Labels: bug, s: needs review

#391 refactor: improve `_WebookState` typing
  disnake/channel.py
  disnake/message.py
  disnake/state.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: s: needs review, refactor/typing

#396 fix(converter): move import for `commands.clean_content`
  disnake/ext/commands/converter.py
Labels: bug, s: needs review

#399 Improve semantics
  examples/basic_bot.py
Labels: documentation, s: needs review

#403 fix: role icon/emoji editing
  disnake/http.py
Labels: bug, s: needs review

#400 docs: add missing version directives to new modal changes
  disnake/interactions/base.py
  disnake/interactions/modal.py
Labels: documentation, s: needs review

#408 delete youtube = 755600276941176913
  disnake/enums.py
  docs/api.rst
Labels: breaking change, s: needs review

#413 fix: remove unnecessary gateway ratelimit reset
  disnake/gateway.py
Labels: bug, p: medium, s: needs review

#353 feat: support api v10
  README.md
  disnake/errors.py
  disnake/ext/commands/__init__.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/custom_warnings.py
  disnake/flags.py
  disnake/gateway.py
  disnake/http.py
  docs/api.rst
  docs/ext/commands/api.rst
  docs/intents.rst
  examples/basic_bot.py
  examples/basic_voice.py
  examples/context_menus/basic_contexts_menus.py
  examples/converters.py
  examples/custom_context.py
  examples/modal.py
  examples/slash_commands/autocomplete.py
  examples/slash_commands/converters.py
  examples/slash_commands/injections.py
  examples/slash_commands/old.py
  examples/slash_commands/param.py
  examples/slash_commands/subcmd.py
  examples/user_echo_webhook.py
  examples/views/button/confirm.py
  examples/views/button/counter.py
  examples/views/button/link.py
  examples/views/button/paginator.py
  examples/views/button/row_buttons.py
  examples/views/disable_view.py
  examples/views/ephemeral.py
  examples/views/persistent.py
  examples/views/select/dropdown.py
  examples/views/tic_tac_toe.py
Labels: breaking change, api support, p: medium, s: needs review

#406 fix: delete scheduled events on channel delete
  disnake/state.py
Labels: bug, s: needs review

#407 fix: update types according to latest api-docs changes
  disnake/channel.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/role.py
  disnake/state.py
  disnake/types/channel.py
  disnake/types/guild_scheduled_event.py
  disnake/types/voice.py
Labels: enhancement, s: needs review

#409 fix: remove awkword and sketchy_artist activities
  disnake/enums.py
  docs/api.rst
Labels: breaking change, s: needs review

#410 feat: add boost count to invite guilds
  disnake/invite.py
Labels: enhancement, api support, s: needs review

#423 docs: fix duplicate search results and custom scorer
  docs/_static/scorer.js
  docs/_static/searchtools.js
Labels: bug, documentation, s: needs review

#427 chore: replaced `inspect.iscoroutinefunction` with `asyncio.iscoroutinefunction`
  disnake/ext/commands/cog.py
  disnake/ext/commands/core.py
  disnake/ext/tasks/__init__.py
  disnake/member.py
  disnake/ui/button.py
  disnake/ui/select.py
  docs/extensions/attributetable.py
Labels: enhancement, s: needs review

#419 fix: minor typing and documentation improvements
  disnake/channel.py
  disnake/client.py
  disnake/guild.py
  docs/api.rst
  docs/ext/commands/api.rst
Labels: bug, documentation, p: medium, s: needs review

#432 feat(AuditLog): guild scheduled event image
  disnake/audit_logs.py
  docs/api.rst
Labels: enhancement, api support, s: needs review

#431 fix: console spam when using reload
  disnake/ext/commands/common_bot_base.py
Labels: bug, s: needs review

#394 feat: implement `StageInstance.guild_scheduled_event[_id]`
  disnake/flags.py
  disnake/stage_instance.py
  disnake/types/channel.py
Labels: enhancement, api support, s: needs review
