Repository DisnakeDev/disnake, pull requests merged in 2022-04, with the labels that each got.

#434 feat: add documentation search hotkeys
  docs/_static/custom.js
  docs/_templates/layout.html
Labels: documentation, enhancement, s: needs review

#444 fix(listeners): improve listener unloading behaviour
  disnake/ext/commands/cog.py
Labels: bug, s: needs review

#398 fix: correct NameError by moving import out of type checking clause
  disnake/ext/commands/context.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/params.py
Labels: bug, s: needs review

#442 feat!: update bans to use AsyncIterator pagination
  disnake/__init__.py
  disnake/bans.py
  disnake/guild.py
  disnake/http.py
  disnake/iterators.py
Labels: enhancement, breaking change, api support, s: needs review

#446 docs(modals): fix missing inherited members of `ModalInteraction`
  docs/api.rst
Labels: documentation, s: needs review

#438 fix!: remove store channels
  disnake/channel.py
  disnake/enums.py
  disnake/ext/commands/converter.py
  disnake/guild.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/types/channel.py
  disnake/types/guild.py
  docs/api.rst
  docs/ext/commands/api.rst
  docs/ext/commands/commands.rst
Labels: breaking change, s: needs review, deprecation

#445 feat(thread)!: support `newly_created`, add `on_thread_create` event
  disnake/state.py
  docs/api.rst
Labels: enhancement, breaking change, api support, s: needs review

#451 ci: update pre-commit hooks
  .pre-commit-config.yaml
Labels: p: medium, s: needs review, meta

#411 fix: allow most `content` parameters to be positional, change types to `Optional[str]`
  disnake/abc.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: bug, s: needs review

#454 chore: add missing reason parameter to Thread.edit
  disnake/threads.py
Labels: enhancement, s: needs review

#452 feat: Add simple low-level component example
  examples/low_level_components.py
Labels: documentation

#455 chore: remove deprecated features since version 2.4
  disnake/guild.py
  disnake/invite.py
  disnake/threads.py
Labels: breaking change, deprecation

#440 feat: add stage instance start notification
  disnake/channel.py
  disnake/http.py
Labels: enhancement, api support, s: needs review

#402 feat: add session start limit data
  disnake/client.py
  disnake/http.py
  disnake/shard.py
  docs/api.rst
Labels: enhancement, breaking change, api support, s: needs review

#458 feat: add repr methods to interaction data classes
  disnake/interactions/application_command.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
Labels: enhancement, s: needs review

#443 feat: to_file for Assets, Emojis, Stickers
  disnake/asset.py
Labels: t: enhancement, s: needs review

#439 feat!: add `Locale` enum
  disnake/audit_logs.py
  disnake/enums.py
  disnake/guild.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/user.py
  docs/api.rst
  examples/slash_commands/injections.py
Labels: t: enhancement, breaking change, s: needs review

#430 fix: pass connection state to activity emoji
  disnake/activity.py
  disnake/asset.py
  disnake/client.py
  disnake/member.py
  disnake/partial_emoji.py
  disnake/widget.py
Labels: t: bug, s: needs review

#424 fix: rebind guilds/channels of cached messages after receiving `GUILD_CREATE` events
  disnake/state.py
Labels: t: bug, s: needs review

#469 feat: interaction expires and InteractionMessage.edit
  disnake/interactions/base.py
  docs/api.rst
Labels: t: bug, t: enhancement, s: needs review

#416 fix: don't clear caches of stage instances and scheduled events on update
  disnake/guild.py
Labels: t: bug, p: medium, s: needs review

#429 fix: support interactions in `UserConverter`/`MemberConverter`
  disnake/app_commands.py
  disnake/ext/commands/converter.py
Labels: t: bug, s: needs review

#436 docs: fix `invalid escape sequence` warnings
  disnake/abc.py
  disnake/audit_logs.py
  disnake/ext/commands/context.py
  disnake/ext/commands/core.py
  disnake/ext/tasks/__init__.py
  disnake/file.py
  disnake/flags.py
  disnake/guild.py
  disnake/invite.py
  disnake/member.py
  disnake/message.py
  disnake/permissions.py
  disnake/ui/select.py
  disnake/utils.py
Labels: t: documentation, s: needs review

#466 feat: support embed images in interaction edit_message
  disnake/interactions/base.py
Labels: t: enhancement, p: medium, s: needs review

#470 docs: fix several missing/broken entries
  disnake/appinfo.py
  disnake/channel.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  docs/api.rst
  docs/ext/commands/api.rst
Labels: t: documentation, p: low, s: needs review

#425 fix: rebind additional cached references on shard reconnect
  disnake/message.py
  disnake/state.py
Labels: t: bug, s: needs review

#467 chore: add workaround for missing message content intent
  disnake/http.py
  docs/intents.rst
Labels: t: enhancement, api support, p: high

#456 chore/add missing channel create options
  disnake/guild.py
Labels: t: enhancement, p: medium, s: needs review

#464 feat: add support for `last_pin_timestamp`
  disnake/channel.py
  disnake/state.py
  disnake/threads.py
  disnake/types/channel.py
  disnake/types/raw_models.py
  disnake/types/threads.py
Labels: t: enhancement, api support, s: needs review

#428 feat!: rewrite `GuildScheduledEvent.fetch_users` to be an async iterator
  disnake/guild_scheduled_event.py
  disnake/iterators.py
Labels: t: enhancement, breaking change, s: needs review

#422 fix!: improve validation of application command/option names
  disnake/app_commands.py
  disnake/ext/commands/slash_core.py
Labels: t: bug, breaking change, s: needs review

#473 fix: `after` parameter of audit log iterator
  disnake/guild.py
  disnake/http.py
  disnake/iterators.py
  disnake/types/audit_log.py
Labels: t: bug, breaking change, s: needs review

#415 feat: allow passing assets instead of `bytes` for image parameters
  disnake/asset.py
  disnake/channel.py
  disnake/client.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/http.py
  disnake/role.py
  disnake/template.py
  disnake/user.py
  disnake/utils.py
  disnake/webhook/async_.py
  docs/api.rst
  docs/conf.py
Labels: t: enhancement, s: needs review

#475 feat: Add filename and description params to Asset.to_file
  disnake/asset.py
Labels: t: enhancement, s: needs review

#476 chore: update invite link to vanity invite
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  disnake/guild.py
  docs/conf.py
Labels: t: documentation

#461 feat: add missing text related methods to voice channels
  disnake/channel.py
  disnake/webhook/async_.py
Labels: t: enhancement, s: needs review

#457 fix: allow providing None for attachments to clear attachments when editing a message
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: bug, p: medium, s: needs review

#480 feat: provide a default argument for topic when creating a stage channel
  disnake/guild.py
Labels: t: enhancement, s: needs review

#479 feat: add create_forum_posts permission alias
  disnake/channel.py
  disnake/permissions.py
Labels: t: enhancement, s: needs review

#478 fix: add `__str__` to `ApplicationCommand`
  disnake/app_commands.py
  disnake/ext/commands/interaction_bot_base.py
Labels: t: bug, p: low, s: needs review

#486 feat(debug): add logging of what was sent to a webhook
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement

#477 feat!: Voice region strings and VoiceRegion data class
  disnake/__init__.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/client.py
  disnake/enums.py
  disnake/guild.py
  disnake/template.py
  disnake/voice_region.py
  docs/api.rst
Labels: t: enhancement, breaking change, api support, s: needs review, t: refactor/typing

#493 fix: make disnake.types.interactions importable at runtime
  disnake/types/interactions.py
Labels: t: bug, s: needs review

#339 feat: implement guild welcome screen
  disnake/__init__.py
  disnake/guild.py
  disnake/http.py
  disnake/invite.py
  disnake/types/welcome_screen.py
  disnake/welcome_screen.py
  docs/api.rst
Labels: t: enhancement, api support, s: needs review

#497 feat: ability to create news channels
  disnake/guild.py
Labels: t: enhancement, s: needs review

#485 feat: add Member.role_icon property to display rendered role icon
  disnake/member.py
Labels: t: enhancement, s: needs review

#495 feat: add raw_thread_delete, raw_thread_update, and raw_thread_member_remove events
  disnake/raw_models.py
  disnake/state.py
  disnake/types/raw_models.py
  docs/api.rst
Labels: t: enhancement, s: needs review

#483 feat: implement slash command extras
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
Labels: t: enhancement, s: needs review
