Repository DisnakeDev/disnake, pull requests merged in 2022-01, with the labels that each got.

#242 Use proxied readthedocs API for hoverxref
  docs/conf.py
Labels: bug, documentation, s: needs review

#244 fix(Role): Double @ when mentioning the default role.
  disnake/role.py
Labels: bug, s: needs review

#250 use http version 9
  disnake/http.py
Labels: enhancement, s: needs review

#249 Improve `app_commands.py` typing
  disnake/app_commands.py
  disnake/errors.py
  disnake/http.py
  disnake/integrations.py
  disnake/types/interactions.py
  disnake/utils.py
Labels: s: needs review, refactor

#237 Implement Range in slash commands
  disnake/ext/commands/params.py
  examples/slash_commands/autocomplete.py
  examples/slash_commands/converters.py
  examples/slash_commands/injections.py
  examples/slash_commands/param.py
  test_bot/cogs/injections.py
  test_bot/cogs/slash_commands.py
Labels: enhancement, s: needs review

#245 Implement load_extensions
  disnake/ext/commands/common_bot_base.py
  disnake/utils.py
  docs/api.rst
Labels: enhancement, s: needs review

#256 Improve typing of autocomplete/choices and docstring parser
  disnake/app_commands.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/types/interactions.py
  disnake/utils.py
Labels: s: needs review, refactor/typing

#262 CamelCase style
  examples/views/button/row_buttons.py
Labels: documentation, s: needs review

#264 Implement `LargeInt` in slash commands.
  disnake/ext/commands/params.py
  docs/ext/commands/api.rst
  examples/slash_commands/param.py
  test_bot/cogs/slash_commands.py
Labels: enhancement, s: needs review

#254 Fixed a rare command sync bug
  disnake/ext/commands/interaction_bot_base.py
Labels: bug, p: medium, s: needs review

#234 add taskipy for local dev
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  pyproject.toml
  requirements_dev.txt
Labels: s: needs review, meta

#248 fix: allow deferring messages on component interactions
  disnake/interactions/base.py
Labels: enhancement, s: needs review

#257 chore: add disnake development to licensing in all */__init__.py
  disnake/__init__.py
  disnake/ext/commands/__init__.py
  disnake/types/__init__.py
  disnake/ui/__init__.py
  disnake/webhook/__init__.py
Labels: documentation, s: needs review

#266 Add missing support for reason in `http.py`.
  disnake/guild.py
  disnake/http.py
  disnake/sticker.py
  disnake/types/template.py
  disnake/widget.py
Labels: breaking change, api support, s: needs review, refactor/typing

#263 Improve typing of `http.py` and add guild scheduled events `TypedDict`s
  disnake/errors.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/http.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/guild.py
  disnake/types/guild_scheduled_event.py
  disnake/types/invite.py
  disnake/types/raw_models.py
  disnake/webhook/async_.py
Labels: s: needs review, refactor/typing

#274 Fix `GuildScheduledEvent.fetch_users`
  disnake/guild_scheduled_event.py
  disnake/http.py
Labels: bug, p: medium, s: needs review

#276 Add mypy plugin for `commands.Range` annotations
  disnake/ext/mypy_plugin.py
  docs/ext/commands/slash_commands.rst
Labels: enhancement, s: needs review

#267 Improve validation of slash command/option names
  disnake/app_commands.py
Labels: enhancement, s: needs review

#252 fix: bugs with link buttons
  disnake/ui/view.py
Labels: bug, p: medium, s: needs review

#203 feat: add embed default color attribute
  disnake/embeds.py
Labels: enhancement, s: in progress

#283 fix: `Union` in slash commands raising an error
  disnake/ext/commands/params.py
Labels: bug, p: high, s: needs review

#284 fix: message converter now reattempts to fetch messages
  disnake/ext/commands/converter.py
Labels: bug, s: needs review

#297 feat: add missing attributes to invite guild objects
  disnake/invite.py
Labels: enhancement, api support, s: needs review

#285 feat: add thread create_timestamp
  disnake/threads.py
  disnake/types/threads.py
Labels: enhancement, s: needs review

#304 Improve member deserialization with separate user data
  disnake/guild_scheduled_event.py
  disnake/interactions/application_command.py
  disnake/member.py
  disnake/types/member.py
  disnake/user.py
Labels: s: needs review, refactor/typing

#299 Add separate types for command objects returned by the API
  disnake/app_commands.py
  disnake/client.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/guild.py
  disnake/state.py
  docs/api.rst
Labels: s: needs review, refactor/typing

#295 docs(Thread): add deprecation warning to `archiver_id`
  disnake/threads.py
Labels: documentation, s: needs review

#291 feat(Message): add thread property
  disnake/message.py
  disnake/types/message.py
Labels: enhancement, api support, s: needs review

#286 refactor Permission classmethods
  disnake/permissions.py
Labels: s: needs review, refactor/typing

#280 feat(GuildScheduledEvent): add support for image
  disnake/asset.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/http.py
  disnake/types/guild_scheduled_event.py
  disnake/webhook/async_.py
  test_bot/cogs/guild_scheduled_events.py
  test_bot/main.py
Labels: enhancement, api support, s: needs review, s: waiting for api/docs

#306 feat(PartyType): add sketch_heads and ocho activities
  disnake/enums.py
  docs/api.rst
Labels: enhancement, api support, s: needs review

#305 feat: support disnake.Thread annotations in slash command params
  disnake/channel.py
  disnake/ext/commands/params.py
Labels: enhancement, p: medium, s: needs review

#233 add more pre-commit hooks
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  docs/discord.rst
  docs/ext/commands/cogs.rst
  docs/intro.rst
  docs/locale/ja/LC_MESSAGES/api.po
  docs/locale/ja/LC_MESSAGES/discord.po
  docs/locale/ja/LC_MESSAGES/ext/commands/api.po
  docs/locale/ja/LC_MESSAGES/ext/commands/cogs.po
  docs/locale/ja/LC_MESSAGES/ext/commands/commands.po
  docs/locale/ja/LC_MESSAGES/ext/commands/extensions.po
  docs/locale/ja/LC_MESSAGES/ext/commands/index.po
  docs/locale/ja/LC_MESSAGES/ext/tasks/index.po
  docs/locale/ja/LC_MESSAGES/faq.po
  docs/locale/ja/LC_MESSAGES/index.po
  docs/locale/ja/LC_MESSAGES/intro.po
  docs/locale/ja/LC_MESSAGES/logging.po
  docs/locale/ja/LC_MESSAGES/migrating.po
  docs/locale/ja/LC_MESSAGES/migrating_to_async.po
  docs/locale/ja/LC_MESSAGES/quickstart.po
  docs/locale/ja/LC_MESSAGES/sphinx.po
  docs/locale/ja/LC_MESSAGES/version_guarantees.po
  docs/locale/ja/LC_MESSAGES/whats_new.po
  docs/version_guarantees.rst
Labels: s: needs review, meta

#279 Minor refactor of interaction types
  disnake/ext/commands/interaction_bot_base.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/message.py
  disnake/state.py
  disnake/types/interactions.py
  disnake/types/message.py
  docs/api.rst
Labels: s: needs review, refactor/typing

#316 fix: move the mypy plugin to a module
  disnake/ext/mypy_plugin/__init__.py
  setup.py
Labels: p: high, s: needs review

#289 feat: support timeouts in permissions_for
  disnake/abc.py
  disnake/channel.py
  disnake/threads.py
Labels: enhancement, s: needs review

#309 docs(Invite): deprecate revoked
  disnake/invite.py
Labels: documentation, s: needs review

#241 Fix placement of `attachments` array in interaction response payload
  disnake/http.py
  disnake/webhook/async_.py
  test_bot/cogs/misc.py
  test_bot/main.py
Labels: bug, api support, s: needs review

#292 Improve `converter.py` annotations
  disnake/ext/commands/converter.py
Labels: s: needs review, refactor/typing

#307 Update paginator example.
  examples/views/button/paginator.py
Labels: documentation, s: needs review

#308 Add annotations to `gateway.py`
  disnake/gateway.py
  disnake/http.py
  disnake/types/gateway.py
  disnake/voice_client.py
Labels: s: needs review, refactor/typing

#320 Fixed dynamic cooldown (BucketType.default case)
  disnake/ext/commands/cooldowns.py
Labels: bug, s: needs review
