Repository DisnakeDev/disnake, pull requests merged in 2022-08, with the labels that each got.

#594 typing: add gateway event types
  changelog/594.misc.rst
  disnake/automod.py
  disnake/invite.py
  disnake/member.py
  disnake/message.py
  disnake/raw_models.py
  disnake/state.py
  disnake/types/activity.py
  disnake/types/appinfo.py
  disnake/types/automod.py
  disnake/types/gateway.py
  disnake/types/interactions.py
  disnake/types/invite.py
  disnake/types/raw_models.py
  disnake/types/threads.py
  disnake/types/voice.py
  disnake/voice_client.py
Labels: bug, p: low, s: needs review, t: refactor/typing/lint

#672 fix!: change ignore_timeout default in permissions_for to False
  changelog/672.breaking.rst
  disnake/abc.py
  disnake/threads.py
Labels: t: enhancement, breaking change, p: medium, s: needs review, t: refactor/typing/lint

#674 build: add check-manifest, update `MANIFEST.in`
  .github/workflows/lint-test.yml
  MANIFEST.in
  noxfile.py
  pyproject.toml
  requirements/requirements_tools.txt
  setup.py
Labels: p: high, s: needs review, t: dependencies, t: meta, skip news

#676 docs: port changelog from v2.4.1
  docs/whats_new.rst
Labels: t: documentation, s: needs review, skip news

#677 docs: port changelog from v2.5.2
  docs/whats_new.rst
Labels: t: documentation, s: needs review, skip news

#696 build(deps): update slotscheck to 0.15.0
  requirements/requirements_dev.txt
Labels: p: low, s: needs review, t: dependencies, skip news

#701 fix(lint): ignore S311 due to flake8/bandit bug
  .flake8
Labels: p: medium, s: needs review, t: meta, skip news

#617 feat: Infer ScheduledEvent.entity_type
  changelog/590.breaking.rst
  changelog/590.feature.rst
  disnake/guild.py
  disnake/guild_scheduled_event.py
Labels: t: enhancement, s: needs review

#689 fix: check for `command_prefix=None` before warning about message content intent
  changelog/689.deprecate.rst
  changelog/689.doc.rst
  disnake/ext/commands/bot.py
  disnake/ext/commands/bot_base.py
Labels: t: documentation, p: low, s: needs review, t: deprecation

#681 fix: properly close sockets on voice server update
  changelog/488.bugfix.rst
  disnake/voice_client.py
Labels: p: low, s: needs review, t: bugfix

#700 fix(docs): remove symlinks, update lint config
  .flake8
  .pre-commit-config.yaml
  changelog/590.breaking.rst
  changelog/615.feature.rst
  changelog/648.doc.rst
Labels: p: medium, s: needs review, t: meta, skip news

#702 deps: don't install cchardet on py >3.9
  changelog/702.misc.rst
  requirements/requirements_speed.txt
Labels: p: low, s: needs review, t: dependencies, backport needed: 2.5

#706 chore: remove test guilds from test bot due to now instant registration
  test_bot/main.py
Labels: t: meta, skip news

#690 fix(docs): enable `parallel_read_safe` for all sphinx extensions
  changelog/690.misc.rst
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  docs/extensions/exception_hierarchy.py
  docs/extensions/nitpick_file_ignorer.py
  docs/extensions/resourcelinks.py
  noxfile.py
Labels: t: documentation, p: low, s: needs review, t: meta

#698 feat(automod): add mention spam type and new audit log action types
  changelog/698.feature.rst
  disnake/audit_logs.py
  disnake/automod.py
  disnake/enums.py
  disnake/guild.py
  disnake/types/automod.py
  docs/api.rst
Labels: t: enhancement, t: api support, p: medium, s: needs review

#704 lint: validate changelog names start with numbers and end with rst
  .pre-commit-config.yaml
Labels: t: meta, skip news

#711 docs: remove note about appcmd localizations build override
  changelog/711.doc.rst
  docs/ext/commands/slash_commands.rst
Labels: t: documentation, p: low, s: needs review

#653 fix: check the type of the name when validating slash command and option names
  changelog/653.bugfix.rst
  disnake/app_commands.py
Labels: t: bugfix

#708 feat: typed permissions
  .github/workflows/lint-test.yml
  .libcst.codemod.yaml
  changelog/708.feature.rst
  disnake/abc.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/permissions.py
  disnake/ui/select.py
  disnake/utils.py
  noxfile.py
  pyproject.toml
  requirements/requirements_tools.txt
  scripts/__init__.py
  scripts/codemods/__init__.py
  scripts/codemods/kwarg_permissions.py
  scripts/codemods/overloads_no_missing.py
  tests/test_permissions.py
Labels: t: enhancement, p: medium, s: needs review

#710 docs: improve documentation of `strict` kwarg on getch methods
  changelog/710.doc.rst
  disnake/client.py
  disnake/guild.py
Labels: t: documentation, p: low, s: needs review

#691 refactor: improve sphinx extensions
  docs/_static/disnake.svg
  docs/_templates/layout.html
  docs/conf.py
  docs/extensions/_types.py
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  docs/extensions/exception_hierarchy.py
  docs/extensions/nitpick_file_ignorer.py
  docs/extensions/resourcelinks.py
  docs/images/drop_down_icon.svg
  requirements/requirements_docs.txt
Labels: t: documentation, p: low, s: needs review, t: refactor/typing/lint, t: bugfix, skip news

#694 chore: update guild feature list
  disnake/guild.py
  disnake/types/guild.py
Labels: t: documentation, s: needs review, skip news

#714 Revert "feat: add nsfw field to application commands (#528)"
  changelog/528.feature.rst
  disnake/app_commands.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  disnake/types/interactions.py
Labels: p: high, s: needs review, t: bugfix, skip news

#562 docs: restructure examples and don't hardcode tokens
  examples/background_task.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/converters.py
  examples/custom_context.py
  examples/deleted.py
  examples/edits.py
  examples/guessing_game.py
  examples/interactions/autocomplete.py
  examples/interactions/basic_context_menus.py
  examples/interactions/converters.py
  examples/interactions/injections.py
  examples/interactions/localizations.py
  examples/interactions/low_level_components.py
  examples/interactions/modal.py
  examples/interactions/param.py
  examples/interactions/subcmd.py
  examples/new_member.py
  examples/reaction_roles.py
  examples/reply.py
  examples/secret.py
  examples/slash_commands/old.py
  examples/user_echo_webhook.py
  examples/views/button/confirm.py
  examples/views/button/counter.py
  examples/views/button/link.py
  examples/views/button/paginator.py
  examples/views/button/row_buttons.py
  examples/views/disable_view.py
  examples/views/ephemeral.py
  examples/views/persistent.py
  examples/views/select/dropdown.py
  examples/views/tic_tac_toe.py
Labels: t: documentation, help wanted, s: needs review, t: meta, t: refactor/typing/lint, skip news

#715 fix: message initialization failing with threads and no intents
  changelog/699.bugfix.rst
  changelog/712.bugfix.rst
  disnake/message.py
Labels: p: medium, s: needs review, t: bugfix

#678 Fix app command copies
  changelog/678.bugfix.rst
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/slash_core.py
  tests/ext/commands/test_base_core.py
Labels: p: medium, t: bugfix

#707 feat: add on_raw_member events
  changelog/638.feature.rst
  disnake/raw_models.py
  disnake/state.py
  docs/api.rst
Labels: t: enhancement, s: needs review

#649 feat: add application command flag
  changelog/649.feature.rst
  disnake/flags.py
Labels: t: enhancement, t: api support, p: low, s: needs review

#705 fix!: persist other features when changing the community feature
  changelog/705.bugfix.rst
  disnake/guild.py
Labels: breaking change, p: high, s: needs review, t: bugfix

#719 docs: commands.has_permissions includes timeouts.
  changelog/318.breaking.rst
  changelog/672.breaking.0.rst
  changelog/672.breaking.1.rst
  disnake/ext/commands/core.py
Labels: t: documentation, s: needs review

#720 docs: remove references to public guilds and refer to them as community
  changelog/720.doc.rst
  disnake/guild.py
Labels: t: documentation, s: needs review

#247 feat: refactor test bot launcher and config
  .flake8
  .gitignore
  changelog/247.misc.rst
  requirements/requirements_dev.txt
  test_bot/__init__.py
  test_bot/__main__.py
  test_bot/cogs/events.py
  test_bot/cogs/guild_scheduled_events.py
  test_bot/cogs/injections.py
  test_bot/cogs/localization.py
  test_bot/cogs/message_commands.py
  test_bot/cogs/misc.py
  test_bot/cogs/slash_commands.py
  test_bot/cogs/user_commands.py
  test_bot/config.py
  test_bot/example.env
  test_launcher.py
Labels: t: enhancement, s: needs review, t: refactor/typing/lint

#685 refactor(activity)!: improve typing, remove redundancies, fix `Spotify` fields raising errors
  changelog/685.breaking.rst
  changelog/685.bugfix.rst
  changelog/685.doc.rst
  changelog/685.feature.rst
  disnake/activity.py
  disnake/types/activity.py
  docs/api.rst
Labels: breaking change, p: medium, s: needs review, t: refactor/typing/lint, t: bugfix
