Repository DisnakeDev/disnake, pull requests merged in 2022-06, with the labels that each got.

#471 feat!: replace InvalidArgument with TypeError and ValueError
  disnake/abc.py
  disnake/app_commands.py
  disnake/asset.py
  disnake/channel.py
  disnake/client.py
  disnake/errors.py
  disnake/gateway.py
  disnake/guild.py
  disnake/http.py
  disnake/integrations.py
  disnake/message.py
  disnake/opus.py
  disnake/partial_emoji.py
  disnake/reaction.py
  disnake/role.py
  disnake/shard.py
  disnake/stage_instance.py
  disnake/template.py
  disnake/user.py
  disnake/utils.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  docs/api.rst
Labels: breaking change, p: high, s: needs review, t: refactor/typing

#529 test: initial setup
  .github/CONTRIBUTING.md
  .github/actions/setup-env/action.yml
  .github/workflows/lint-test.yml
  .github/workflows/lint.yml
  .gitignore
  disnake/utils.py
  noxfile.py
  pyproject.toml
  requirements/requirements_dev.txt
  requirements/requirements_docs.txt
  requirements/requirements_speed.txt
  requirements/requirements_tools.txt
  requirements/requirements_voice.txt
  requirements_dev.txt
  setup.py
  task.env
  tests/__init__.py
  tests/helpers.py
  tests/test_colour.py
  tests/test_object.py
  tests/test_utils.py
Labels: t: bug, p: high, t: dependencies, t: meta

#550 feat: forum channel webhooks
  disnake/channel.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement, api support

#549 fix: make interaction data dataclasses dicts
  disnake/interactions/application_command.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
Labels: t: enhancement, p: medium, s: needs review

#554 docs: update `CONTRIBUTING.md` and move to repository root
  CONTRIBUTING.md
Labels: t: documentation, p: low, s: needs review, t: meta

#462 refactor(ActionRow)!: more strict typing and other minor upgrades
  disnake/abc.py
  disnake/channel.py
  disnake/components.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/message.py
  disnake/types/components.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/modal.py
  disnake/ui/select.py
  disnake/ui/view.py
  disnake/webhook/async_.py
  docs/api.rst
  requirements/requirements_dev.txt
  tests/ui/test_action_row.py
Labels: t: refactor/typing

#553 docs: add note about build override requirement for localization
  docs/ext/commands/slash_commands.rst
Labels: t: documentation, s: needs review

#435 refactor!: rework embeds
  disnake/abc.py
  disnake/embeds.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/ui/button.py
  disnake/webhook/async_.py
  pyproject.toml
  tests/test_embeds.py
Labels: t: bug, breaking change, s: needs review, t: refactor/typing

#537 feat: use session start data when connecting
  disnake/client.py
  disnake/errors.py
  disnake/shard.py
  docs/api.rst
Labels: t: enhancement, s: in progress, s: needs review

#531 change default sticker limit to 5
  disnake/guild.py
Labels: t: enhancement, api support, s: needs review, s: waiting for api/docs

#498 feat: use recipient and icon data for group dms in invites
  disnake/invite.py
  disnake/types/channel.py
  disnake/types/invite.py
Labels: t: enhancement, api support, s: needs review

#532 feat: improve audit log targets
  disnake/abc.py
  disnake/audit_logs.py
  disnake/enums.py
  disnake/guild_scheduled_event.py
  disnake/integrations.py
  disnake/invite.py
  disnake/iterators.py
  disnake/state.py
  disnake/types/audit_log.py
  disnake/types/integration.py
  docs/api.rst
Labels: t: enhancement, p: medium, s: needs review

#548 fix!: rename scheduled event parameter `channel_id` to `channel`, fix validation
  disnake/guild.py
  disnake/guild_scheduled_event.py
  test_bot/cogs/guild_scheduled_events.py
Labels: t: bug, t: enhancement, breaking change, p: low, s: needs review

#561 feat: add `GuildScheduledEvent.created_at` and `.url` properties
  disnake/guild_scheduled_event.py
Labels: t: enhancement, p: low

#560 fix!: raise `TypeError` instead of `ValueError` in scheduled events validation
  disnake/guild.py
  disnake/guild_scheduled_event.py
Labels: t: bug, breaking change, s: needs review

#546 fix!: update audit log fields + docs
  disnake/audit_logs.py
  docs/api.rst
Labels: t: bug, t: documentation, breaking change, p: low, s: needs review

#559 typing: update pyright to 1.1.254, fix new errors
  disnake/components.py
  disnake/errors.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/view.py
  disnake/iterators.py
  disnake/ui/action_row.py
  disnake/widget.py
  docs/conf.py
  requirements/requirements_dev.txt
  tests/ext/commands/test_core.py
Labels: s: needs review, t: dependencies, t: refactor/typing

#564 ci: run docs creation in workflows
  .github/workflows/lint-test.yml
  noxfile.py
Labels: t: documentation, s: needs review, t: meta

#563 typing: update command decorators, fix item typevar bounds
  disnake/ext/commands/base_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
Labels: s: needs review, t: refactor/typing

#519 typing: run pyright on examples
  examples/background_task.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/converters.py
  examples/slash_commands/subcmd.py
  examples/user_echo_webhook.py
  examples/views/select/dropdown.py
  pyproject.toml
Labels: t: documentation, s: blocked, s: needs review, t: refactor/typing

#566 docs: update the PyPI URL & minor wording
  README.md
  docs/index.rst
Labels: t: documentation, s: needs review

#569 fix: assume None is an empty channel name for guild channels
  disnake/channel.py
  disnake/types/channel.py
Labels: t: bug, p: high, s: needs review

#572 fix: update identify properties
  disnake/gateway.py
  disnake/types/gateway.py
Labels: t: bug, api support, s: needs review, s: waiting for api/docs

#568 fix: handle `default_auto_archive_duration` enum value in channel edits
  disnake/abc.py
  disnake/enums.py
Labels: t: bug, backport needed: 2.5

#571 feat: add bitrate param in create_stage_channel
  disnake/guild.py
Labels: t: enhancement, api support, s: needs review

#574 feat: add `Guild.edit_mfa_level`
  disnake/guild.py
  disnake/http.py
  disnake/types/guild.py
Labels: t: enhancement, api support, p: low, s: needs review

#580 chore: add more typings to GuildCommandInteraction
  disnake/interactions/application_command.py
Labels: p: low, s: needs review, t: refactor/typing

#582 feat: add `slowmode_delay` parameter to `create_voice_channel`
  disnake/guild.py
Labels: t: enhancement, api support, p: low, s: needs review

#576 docs: make guild invite documentation clearer regarding vanity invites
  disnake/guild.py
Labels: t: documentation, p: low, s: needs review
