Repository DisnakeDev/disnake, pull requests merged in 2022-05, with the labels that each got.

#474 feat: add suppress_embeds parameter to sending messages
  disnake/abc.py
  disnake/channel.py
  disnake/flags.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement, api support, s: needs review

#504 feat(ForumChannel): return message when creating thread
  disnake/channel.py
  disnake/http.py
  disnake/types/threads.py
Labels: t: enhancement, api support, s: needs review

#506 docs: mark what classes implement Command abcs
  disnake/abc.py
  disnake/app_commands.py
  disnake/ext/commands/base_core.py
  disnake/ui/item.py
Labels: t: documentation, p: low, s: needs review

#269 feat: implement application command localizations
  .gitignore
  disnake/__init__.py
  disnake/app_commands.py
  disnake/client.py
  disnake/custom_warnings.py
  disnake/enums.py
  disnake/errors.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/http.py
  disnake/i18n.py
  disnake/interactions/base.py
  disnake/state.py
  disnake/types/interactions.py
  disnake/utils.py
  docs/api.rst
  docs/ext/commands/slash_commands.rst
  examples/localizations.py
  test_bot/cogs/localization.py
  test_bot/locale/de.json
  test_bot/main.py
Labels: t: enhancement, api support, s: needs review

#465 feat(MessageTypes): add `auto_moderation_action` type
  disnake/enums.py
  docs/api.rst
Labels: t: enhancement, api support, s: needs review

#508 fix: audio delay when calling after
  disnake/player.py
Labels: t: bug, s: needs review

#510 docs: update `on_member_update` to be inclusive of future changes
  docs/api.rst
Labels: t: documentation, s: needs review

#513 feat: add disnake.Message.application_id
  disnake/message.py
Labels: t: enhancement, api support

#512 feat: return namedtuple from `ForumChannel.create_thread`, improve `Thread` repr
  disnake/channel.py
  disnake/threads.py
Labels: t: enhancement, s: needs review

#405 feat!: implement application command permissions v2
  disnake/app_commands.py
  disnake/audit_logs.py
  disnake/client.py
  disnake/enums.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/guild.py
  disnake/http.py
  disnake/interactions/application_command.py
  disnake/state.py
  disnake/types/audit_log.py
  disnake/types/interactions.py
  docs/api.rst
  docs/ext/commands/api.rst
  docs/ext/commands/slash_commands.rst
  test_bot/cogs/slash_commands.py
  test_bot/main.py
Labels: t: enhancement, breaking change, api support

#505 feat!: raise error instead of silently returning on interactions that do not support deferring
  disnake/interactions/base.py
Labels: t: enhancement

#482 typing: update MISSING and incorrect typehints
  disnake/abc.py
  disnake/channel.py
  disnake/client.py
  disnake/guild.py
  disnake/integrations.py
  disnake/message.py
  disnake/stage_instance.py
  disnake/state.py
  disnake/sticker.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: s: needs review, t: refactor/typing

#501 feat(cogs): Add app-command equivalents to `command_attrs` kwarg
  disnake/app_commands.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
Labels: t: enhancement, s: needs review

#514 typing: update pyright, fix new issues
  disnake/audit_logs.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/params.py
  disnake/gateway.py
  disnake/member.py
  docs/conf.py
  requirements_dev.txt
Labels: s: needs review, t: dependencies, t: refactor/typing

#511 docs: misc content/formatting improvements
  disnake/app_commands.py
  disnake/appinfo.py
  disnake/asset.py
  disnake/channel.py
  disnake/client.py
  disnake/custom_warnings.py
  disnake/emoji.py
  disnake/errors.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/context.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/help.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/ext/tasks/__init__.py
  disnake/i18n.py
  disnake/integrations.py
  disnake/interactions/application_command.py
  disnake/iterators.py
  disnake/message.py
  disnake/partial_emoji.py
  disnake/player.py
  disnake/role.py
  disnake/widget.py
  docs/api.rst
  docs/ext/commands/commands.rst
  docs/ext/commands/slash_commands.rst
Labels: t: documentation, s: needs review

#420 release: add changelog for v2.5.0, bump version
  disnake/__init__.py
  docs/whats_new.rst
Labels: s: in progress, t: release

#515 chore: update version to 2.6.0 alpha
  disnake/__init__.py
Labels: p: high, s: needs review, t: meta

#521 fix: decorator-based autocompleters
  disnake/ext/commands/slash_core.py
Labels: t: bug, s: needs review

#524 docs: add v2.5.1 changelog
  docs/whats_new.rst
Labels: t: documentation, s: needs review, t: release

#518 docs: update documentation to match new backend v2 behavior
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  docs/ext/commands/additional_info.rst
  docs/ext/commands/slash_commands.rst
  examples/context_menus/basic_contexts_menus.py
Labels: t: documentation, s: needs review

#522 docs(deps): update sphinx to v4.5
  docs/_static/custom.js
  setup.py
Labels: t: documentation, p: low, s: needs review, t: dependencies

#536 fix commands.is_nsfw and reaction_remove for voice channels and threads
  disnake/ext/commands/core.py
  disnake/state.py
Labels: t: bug, s: needs review

#520 fix: handle bool values for `default_member_permissions`
  disnake/app_commands.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/slash_core.py
Labels: t: bug, s: needs review

#539 fix: update intersphinx link for requests
  docs/conf.py
Labels: t: bug, t: documentation, p: high, s: needs review

#534 feat: add `Webhook.application_id`
  disnake/audit_logs.py
  disnake/types/webhook.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  docs/api.rst
Labels: t: enhancement, api support

#538 fix: update `Guild.bitrate_limit` to use correct value for `VIP_REGIONS`
  disnake/guild.py
Labels: t: bug, s: needs review

#542 docs: fix broken `Range` references
  docs/ext/commands/slash_commands.rst
Labels: t: documentation, s: needs review

#526 fix: update guild iterator + scheduled event user iterator
  disnake/guild.py
  disnake/iterators.py
Labels: t: bug, s: needs review

#544 fix: make system info render in a codeblock in github issues
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: t: meta

#535 fix: handle other `type` field types in audit logs
  disnake/audit_logs.py
  docs/api.rst
Labels: t: bug, s: needs review

#541 Add Generation for Documentation Download
  .readthedocs.yml
Labels: t: documentation, t: enhancement, s: needs review

#540 typing: improve guild channel typing
  disnake/abc.py
  disnake/ext/commands/context.py
  disnake/ext/commands/converter.py
  disnake/guild.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/state.py
Labels: t: documentation, s: needs review, t: refactor/typing

#543 typing: more explict "type" typings
  disnake/activity.py
  disnake/channel.py
  disnake/raw_models.py
  disnake/threads.py
  docs/api.rst
Labels: p: low, t: refactor/typing

#547 feat: add channel flags to all channels
  disnake/abc.py
  disnake/channel.py
  disnake/flags.py
  disnake/threads.py
  disnake/types/channel.py
Labels: t: enhancement, api support, p: medium, s: needs review
