Repository DisnakeDev/disnake, pull requests merged in 2022-02, with the labels that each got.

#300 feat: check `guild_ids` and `test_guilds`
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
Labels: enhancement, s: needs review

#325 fix: error when checking test_guilds/guild_ids
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
Labels: bug, s: needs review

#328 fix: error when creating a sticker
  disnake/guild.py
  disnake/types/sticker.py
Labels: bug, p: low, s: needs review

#333 fix(Guild): missing return in `get_command`
  disnake/guild.py
Labels: bug, s: needs review

#332 Fix undesired behavior
  examples/views/disable_view.py
Labels: documentation, s: needs review

#226 Add attachment option type for slash commands
  disnake/ext/commands/params.py
  disnake/interactions/application_command.py
  disnake/types/interactions.py
  docs/api.rst
  docs/ext/commands/slash_commands.rst
Labels: enhancement, api support, s: needs review

#338 fix: slash commands options with no description
  disnake/app_commands.py
  disnake/ext/commands/params.py
Labels: bug, p: high, s: needs review

#321 touch up permissions
  disnake/abc.py
  disnake/channel.py
  disnake/guild.py
  disnake/interactions/base.py
  disnake/permissions.py
Labels: breaking change, p: high, s: needs review

#334 Making guild.chunk() return a list of guild members.
  disnake/guild.py
Labels: enhancement, s: needs review

#340 Backport #338 to 2.3
  disnake/__init__.py
  disnake/ext/commands/params.py
  docs/whats_new.rst
Labels: bug, p: high

#343 Update banner.png
  assets/banner.png
Labels: s: needs review, meta

#346 fix(slashcmd): improve handling of uppercase slash command names
  disnake/ext/commands/slash_core.py
Labels: bug, s: needs review

#349 `GuildChannel.set_permissions` kwargs can be `None`
  disnake/abc.py
Labels: refactor/typing

#322 feat(Guild): add get_or_fetch_members
  disnake/guild.py
Labels: enhancement, s: needs review

#319 feat: jump to channel properties
  disnake/abc.py
  disnake/channel.py
  disnake/threads.py
Labels: enhancement, s: needs review

#278 Docs header/sidebar/layout cleanup
  docs/_static/custom.js
  docs/_static/sidebar.js
  docs/_static/style.css
  docs/_static/touch.js
  docs/_templates/genindex.html
  docs/_templates/layout.html
  docs/conf.py
  docs/extensions/attributetable.py
  docs/extensions/details.py
  docs/images/disnake.svg
  pyproject.toml
  setup.py
Labels: documentation, enhancement, s: needs review

#348 chore: add changelog for v2.4.0, bump version
  disnake/__init__.py
  disnake/__main__.py
  disnake/permissions.py
  docs/ext/commands/api.rst
  docs/ext/commands/slash_commands.rst
  docs/whats_new.rst
Labels: documentation, s: in progress

#354 chore: update version indicator to 2.5.0 alpha
  disnake/__init__.py
Labels: meta

#352 fix: improve components parameter docs and `isinstance` check
  disnake/abc.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/ui/action_row.py
  disnake/webhook/async_.py
Labels: bug, documentation, s: needs review

#361 deprecate: integration create, edit, sync and delete
  disnake/guild.py
  disnake/integrations.py
  disnake/utils.py
Labels: s: needs review, deprecation

#360 feat: add widget settings, widget images
  disnake/enums.py
  disnake/guild.py
  disnake/http.py
  disnake/widget.py
  docs/api.rst
Labels: enhancement, api support, s: needs review

#356 chore: use the proper http method for joining threads and remove unused methods
  disnake/http.py
  disnake/member.py
  disnake/types/member.py
Labels: s: needs review

#355 breaking: require one of message or type for creating a thread
  disnake/channel.py
Labels: breaking change, api support, s: needs review

#366 feat: support reason for `Message.create_thread` and `Thread.delete`
  disnake/message.py
  disnake/threads.py
Labels: enhancement, s: needs review

#362 fix: add commands.errors.LargeIntConversionFailure
  disnake/ext/commands/errors.py
  disnake/ext/commands/params.py
Labels: enhancement, breaking change, s: needs review

#363 feat: add `message` field to `ModalInteraction`
  disnake/interactions/modal.py
  disnake/types/interactions.py
Labels: enhancement, api support, s: needs review

#364 feat: support edit responses for modal interactions
  disnake/errors.py
  disnake/interactions/base.py
Labels: enhancement, s: blocked, s: needs review

#359 feat: add GuildPreview
  disnake/__init__.py
  disnake/client.py
  disnake/emoji.py
  disnake/guild_preview.py
  disnake/http.py
  disnake/types/guild.py
  docs/api.rst
Labels: api support, s: needs review

#357 deprecate and update voice regions
  disnake/client.py
  disnake/enums.py
  disnake/guild.py
  disnake/http.py
  disnake/template.py
  disnake/types/voice.py
Labels: breaking change, s: needs review, deprecation

#372 update doc of `disnake.Guild.create_template`
  disnake/guild.py
Labels: documentation, s: needs review

#373 fix Permissions.private_channel
  disnake/permissions.py
Labels: bug, s: needs review

#369 chore: deprecate summary on application objects
  disnake/appinfo.py
  disnake/integrations.py
Labels: s: needs review, deprecation

#380 fix: no longer shadow disnake.message with disnake.interactions.message
  disnake/interactions/__init__.py
  disnake/webhook/__init__.py
Labels: bug, s: needs review

#377 Docs: post cleanup bugfixes
  docs/_static/custom.js
  docs/_static/sidebar.js
  docs/_static/style.css
  docs/_templates/layout.html
Labels: bug, documentation, s: needs review

#378 fix: improve typing of `Messageable.send` and http methods
  disnake/abc.py
  disnake/http.py
  disnake/interactions/base.py
Labels: s: needs review, refactor/typing

#311 Fix remaining pyright issues, add pyright CI
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lint.yml
  .github/workflows/pre-commit.yml
  .gitignore
  disnake/channel.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  disnake/flags.py
  disnake/guild.py
  disnake/interactions/base.py
  disnake/member.py
  disnake/message.py
  disnake/opus.py
  disnake/player.py
  disnake/raw_models.py
  disnake/reaction.py
  disnake/state.py
  disnake/types/raw_models.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
  disnake/ui/view.py
  disnake/utils.py
  disnake/voice_client.py
  pyproject.toml
  requirements_dev.txt
  task.env
Labels: enhancement, s: needs review, meta, refactor/typing
