Repository DisnakeDev/disnake, pull requests merged in 2022-09, with the labels that each got.

#727 docs: fix link to parameter injections example
  docs/ext/commands/slash_commands.rst
  docs/whats_new.rst
Labels: t: documentation, p: medium, s: needs review, skip news

#728 fix: don't provide message content intent with Intents.all()
  disnake/flags.py
Labels: p: high, t: bugfix, backport: 2.4

#673 fix: make commands.(bot_)has_permissions work without the bot in server
  changelog/673.bugfix.rst
  disnake/ext/commands/core.py
Labels: p: low, s: needs review, t: bugfix

#729 feat: add `BotIntegration.scopes`
  changelog/729.feature.rst
  disnake/integrations.py
  disnake/types/integration.py
Labels: t: enhancement, t: api support, s: needs review

#731 docs: unify #522 and #565 changelog entries
  changelog/522.doc.rst
  changelog/565.doc.rst
Labels: t: documentation, skip news

#401 feat: pass deserialization exceptions in gateway event handler to loop exception handler
  changelog/401.breaking.rst
  changelog/401.feature.rst
  disnake/client.py
  disnake/gateway.py
  docs/api.rst
  test_bot/__main__.py
  test_bot/config.py
  test_bot/example.env
Labels: t: enhancement, breaking change, s: needs review

#686 feat(activity): add undocumented fields
  disnake/activity.py
  disnake/types/activity.py
Labels: t: enhancement, t: api support, p: low, s: needs review, skip news

#616 tests(flags): test operations on flag classes and values and flag logic
  changelog/616.feature.rst
  changelog/616.misc.rst
  disnake/flags.py
  tests/test_flags.py
Labels: s: needs review, t: tests

#371 feat(client)!: Make kwargs for 'public api' Client classes explicit, disallow superfluous kwargs
  changelog/371.breaking.rst
  disnake/client.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/shard.py
  disnake/state.py
  test_bot/config.py
Labels: t: enhancement, breaking change, s: needs review

#730 Support new thread and message attributes (position, message_count, total_message_sent)
  changelog/640.feature.rst
  disnake/message.py
  disnake/state.py
  disnake/threads.py
  disnake/types/channel.py
  disnake/types/message.py
  disnake/types/threads.py
Labels: t: enhancement, t: api support, s: needs review

#718 feat: support INVITES_DISABLED guild feature
  changelog/718.feature.rst
  disnake/guild.py
  disnake/types/guild.py
Labels: t: enhancement, s: needs review

#732 docs: document that messages can be sent with only components
  disnake/abc.py
Labels: t: documentation, skip news

#717 feat: add Interaction.data
  changelog/654.feature.rst
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
Labels: t: enhancement, s: needs review

#738 feat: alias original_message methods to original_response to be less confusing
  changelog/738.feature.rst
  disnake/errors.py
  disnake/interactions/base.py
  docs/api.rst
  test_bot/cogs/guild_scheduled_events.py
Labels: t: enhancement, t: deprecation

#739 fix: make `ForumChannel.create_thread` not require content
  changelog/739.feature.rst
  disnake/channel.py
Labels: p: medium, s: needs review, t: bugfix

#733 feat: view method chaining
  changelog/733.feature.rst
  disnake/ui/view.py
Labels: t: enhancement, s: needs review

#740 feat: return self in actionrow row methods to allow chaining calls
  changelog/740.feature.rst
  disnake/ui/action_row.py
Labels: t: enhancement

#737 feat: save the type of response made by an interaction response
  changelog/737.feature.rst
  disnake/interactions/base.py
  disnake/ui/modal.py
  test_bot/__main__.py
Labels: t: enhancement

#736 feat!: update/fix widget fields
  changelog/736.breaking.rst
  changelog/736.bugfix.rst
  changelog/736.feature.rst
  disnake/activity.py
  disnake/asset.py
  disnake/types/widget.py
  disnake/utils.py
  disnake/widget.py
  docs/api.rst
  tests/test_utils.py
Labels: t: enhancement, breaking change, t: api support, p: medium, s: needs review, t: bugfix

#743 don't use deprecated @! mention syntax
  changelog/743.bugfix.rst
  disnake/member.py
Labels: s: needs review

#744 typing: update options parameter type in `ui.ActionRow.add_select`
  changelog/744.misc.rst
  disnake/ui/action_row.py
  disnake/ui/select.py
Labels: s: needs review, t: refactor/typing/lint

#745 docs: own forum threads can be deleted if there are no replies
  changelog/745.doc.rst
  disnake/threads.py
Labels: t: documentation, s: needs review

#709 feat: implement `resume_gateway_url` handling
  changelog/709.feature.0.rst
  changelog/709.feature.1.rst
  disnake/client.py
  disnake/ext/commands/bot.py
  disnake/gateway.py
  disnake/http.py
  disnake/shard.py
  disnake/types/gateway.py
  docs/api.rst
  tests/test_http.py
Labels: t: enhancement, t: api support, p: high, s: needs review

#746 fix: only send `slowmode_delay` param with `ForumChannel.create_thread` if required
  changelog/746.bugfix.rst
  disnake/channel.py
Labels: p: high, s: needs review, backport: 2.5, t: bugfix

#750 deps: bump pyright to 1.1.271
  disnake/ext/commands/core.py
  disnake/ext/tasks/__init__.py
  disnake/i18n.py
  disnake/ui/item.py
  requirements/requirements_dev.txt
Labels: p: low, s: needs review, t: dependencies, skip news

#749 docs: clarify behavior of flag initializer kwargs with aliases
  changelog/749.doc.rst
  disnake/flags.py
  disnake/permissions.py
  tests/test_flags.py
  tests/test_permissions.py
Labels: t: documentation, s: needs review

#747 fix: don't count initial message in forum threads towards `message_count`
  changelog/747.bugfix.rst
  disnake/state.py
Labels: p: medium, s: needs review, t: bugfix

#751 typing: enable `strictParameterNoneValue` pyright rule
  changelog/751.misc.rst
  disnake/abc.py
  disnake/app_commands.py
  disnake/channel.py
  disnake/client.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/guild.py
  disnake/http.py
  disnake/i18n.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/message.py
  disnake/shard.py
  disnake/state.py
  disnake/voice_client.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  examples/interactions/injections.py
  examples/interactions/param.py
  pyproject.toml
  test_bot/cogs/injections.py
  test_bot/cogs/slash_commands.py
Labels: p: low, s: needs review, t: refactor/typing/lint

#752 docs: add the valid options for afk_timeout
  disnake/guild.py
Labels: t: documentation, s: needs review, skip news

#757 feat: rename with_edits to with_changes
  changelog/757.feature.rst
  disnake/automod.py
Labels: t: enhancement, breaking change, s: needs review

#754 feat: rename start_embedded_activities to use_embedded_activities
  changelog/754.feature.rst
  disnake/abc.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/permissions.py
Labels: t: enhancement, s: needs review, t: deprecation

#755 feat: rename use_slash_commands to use_application_commands
  changelog/755.feature.rst
  disnake/abc.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/permissions.py
Labels: t: enhancement, s: needs review, t: deprecation

#659 feat: implement `clean_history_duration` parameter for bans
  changelog/659.deprecate.rst
  changelog/659.feature.rst
  disnake/guild.py
  disnake/http.py
  disnake/member.py
  docs/ext/commands/commands.rst
Labels: t: enhancement, t: api support, s: needs review

#753 feat: add equal and not equal operators support for `disnake.Embed`
  changelog/742.feature.rst
  disnake/embeds.py
  tests/test_embeds.py
Labels: t: enhancement, s: needs review

#760 docs: fix version directives
  disnake/errors.py
  disnake/interactions/base.py
Labels: t: documentation, p: low, s: needs review, skip news

#761 fix: make svg valid again
  docs/_static/disnake.svg
Labels: t: documentation, p: high, s: needs review, skip news

#762 docs: fix outdated inherited `original_message` aliases
  docs/api.rst
Labels: t: documentation, s: needs review, skip news

#726 feat: implement remaining forum channel features
  changelog/724.feature.rst
  disnake/abc.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/enums.py
  disnake/flags.py
  disnake/guild.py
  disnake/http.py
  disnake/partial_emoji.py
  disnake/threads.py
  disnake/types/channel.py
  disnake/types/threads.py
  docs/api.rst
  tests/test_abc.py
Labels: t: enhancement, t: api support, p: medium, s: needs review

#758 feat: support `defer(with_message=False)` for modal interactions
  changelog/758.feature.rst
  disnake/interactions/base.py
  tests/interactions/test_base.py
Labels: t: enhancement, t: tests

#759 feat: add `parent` attributes to slash subcommands and groups
  changelog/277.feature.rst
  changelog/759.breaking.rst
  disnake/ext/commands/slash_core.py
  tests/ext/commands/test_slash_core.py
Labels: t: enhancement, s: needs review

#675 feat(commands)!: Add support for injected parameters autocompletions
  changelog/669.breaking.rst
  changelog/669.doc.rst
  changelog/670.feature.rst
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  docs/ext/commands/additional_info.rst
  docs/ext/commands/api.rst
Labels: t: enhancement, s: needs review

#768 feat: add backwards-compatible `EmptyEmbed` alias
  changelog/435.breaking.rst
  changelog/435.deprecate.rst
  changelog/768.deprecate.rst
  disnake/embeds.py
  docs/conf.py
  tests/test_embeds.py
Labels: t: enhancement, p: medium, s: needs review

#655 ext.tasks.loop inheritance support
  changelog/655.breaking.rst
  changelog/655.feature.rst
  disnake/ext/tasks/__init__.py
  tests/ext/tasks/test_loops.py
Labels: t: enhancement, p: medium, s: needs review

#769 fix(gateway): default to current url for resuming instead of initial url
  changelog/769.feature.rst
  disnake/gateway.py
Labels: s: needs review, t: bugfix

#770 fix: handle edge case with `Optional[Literal[...]]` parameter annotations
  changelog/770.bugfix.rst
  disnake/ext/commands/params.py
Labels: s: needs review, backport: 2.5, t: bugfix

#716 refactor(examples): general cleanup + improvements
  changelog/562.doc.rst
  changelog/716.doc.rst
  examples/background_task.py
  examples/basic_bot.py
  examples/basic_voice.py
  examples/converters.py
  examples/custom_context.py
  examples/deleted.py
  examples/edit_delete.py
  examples/edits.py
  examples/guessing_game.py
  examples/interactions/autocomplete.py
  examples/interactions/basic_context_menus.py
  examples/interactions/converters.py
  examples/interactions/injections.py
  examples/interactions/localizations.py
  examples/interactions/low_level_components.py
  examples/interactions/modal.py
  examples/interactions/param.py
  examples/interactions/subcmd.py
  examples/new_member.py
  examples/reaction_roles.py
  examples/reply.py
  examples/secret.py
  examples/user_echo_webhook.py
  examples/views/button/confirm.py
  examples/views/button/counter.py
  examples/views/button/ephemeral_counter.py
  examples/views/button/link.py
  examples/views/button/paginator.py
  examples/views/button/row_buttons.py
  examples/views/disable_view.py
  examples/views/ephemeral.py
  examples/views/persistent.py
  examples/views/select/dropdown.py
  examples/views/tic_tac_toe.py
Labels: t: documentation, p: medium, s: needs review

#771 fix: handle edge case with `Optional[Literal[...]]` parameter annotations
  disnake/ext/commands/params.py
Labels: backport: 2.5

#772 deps: don't install cchardet on py >3.9 (#702)
  setup.py
Labels: backport: 2.5

#773 release: v2.5.3
  disnake/__init__.py
  docs/whats_new.rst
Labels: t: release

#774 docs: add v2.5.3 changelog
  docs/whats_new.rst
Labels: t: documentation, skip news

#776 chore: update version to 2.7.0 alpha
  disnake/__init__.py
Labels: t: meta, skip news

#780 fix(docs): fix spelling
  disnake/mentions.py
Labels: t: documentation, skip news

#779 fix(ci): typo in codemod error message on GHA
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#763 deps(docs): update towncrier to v22.8.0
  changelog/_template.rst.jinja
  docs/conf.py
  pyproject.toml
  requirements/requirements_docs.txt
  requirements/requirements_tools.txt
Labels: t: documentation, t: dependencies, skip news

#777 feat(codemod): codemod PermissionOverwrite typings as well
  changelog/777.bugfix.rst
  disnake/permissions.py
  scripts/codemods/typed_permissions.py
Labels: t: enhancement, t: refactor/typing/lint, needs backport: 2.6
