Repository DisnakeDev/disnake, pull requests merged in 2022-07, with the labels that each got.

#588 typing: improve interaction typings
  disnake/types/interactions.py
Labels: p: low, s: needs review, t: refactor/typing

#586 feat: add Interaction.app_permissions
  disnake/interactions/base.py
  disnake/types/interactions.py
Labels: t: enhancement, api support, p: medium, s: needs review

#490 style: formatting improvements
  disnake/__main__.py
  disnake/abc.py
  disnake/activity.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/enums.py
  disnake/errors.py
  disnake/ext/commands/context.py
  disnake/ext/commands/core.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/help.py
  disnake/flags.py
  disnake/gateway.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/member.py
  disnake/message.py
  disnake/player.py
  disnake/raw_models.py
  disnake/ui/view.py
  disnake/utils.py
  disnake/voice_client.py
  docs/extensions/attributetable.py
  tests/test_utils.py
Labels: p: low, s: needs review, t: refactor/typing

#583 fix!: improve interaction component typings
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/types/interactions.py
Labels: t: bug, breaking change, p: high, t: refactor/typing

#584 fix: correctly handle unions in `verify_type`
  disnake/ext/commands/params.py
  tests/ext/commands/test_params.py
Labels: t: bug, p: medium, s: needs review, backport needed: 2.5

#593 feat: string option length limits
  disnake/app_commands.py
  disnake/ext/commands/params.py
  disnake/ext/mypy_plugin/__init__.py
  disnake/types/interactions.py
  docs/ext/commands/api.rst
  docs/ext/commands/slash_commands.rst
Labels: t: enhancement, api support, p: medium, s: needs review

#558 feat: support selects in modals
  disnake/components.py
  disnake/interactions/modal.py
  disnake/ui/action_row.py
  examples/modal.py
  tests/ui/test_action_row.py
Labels: t: enhancement, p: high, s: needs review, s: waiting for api/docs

#598 revert: "feat: support selects in modals (#558)"
  disnake/components.py
  disnake/interactions/modal.py
  disnake/ui/action_row.py
  examples/modal.py
  tests/ui/test_action_row.py
Labels: p: high, t: bugfix

#599 ci: add a workflow checking for a "do not merge" label and block the merge if it exists.
  .github/workflows/check-pull-labels.yaml
Labels: p: high, t: meta

#557 style: flake8
  .flake8
  .github/workflows/lint-test.yml
  .pre-commit-config.yaml
  disnake/ext/commands/base_core.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/gateway.py
  disnake/guild.py
  disnake/http.py
  disnake/i18n.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/member.py
  disnake/mentions.py
  disnake/message.py
  disnake/opus.py
  disnake/permissions.py
  disnake/player.py
  disnake/shard.py
  disnake/state.py
  disnake/threads.py
  disnake/user.py
  disnake/utils.py
  docs/conf.py
  docs/extensions/attributetable.py
  docs/extensions/exception_hierarchy.py
  docs/extensions/resourcelinks.py
  examples/secret.py
  examples/slash_commands/converters.py
  examples/views/button/paginator.py
  examples/views/button/row_buttons.py
  examples/views/tic_tac_toe.py
  noxfile.py
  pyproject.toml
  requirements/requirements_dev.txt
  setup.py
  test_launcher.py
  tests/ext/commands/test_core.py
  tests/test_utils.py
Labels: p: medium, s: needs review, t: refactor/typing

#604 ci: don't run tests on the pull context if on main repo
  .github/workflows/lint-test.yml
Labels: p: high, s: needs review, t: meta

#602 chore(lint): add flake8-comprehensions for catching comprehension mistakes
  disnake/channel.py
  disnake/client.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/flags.py
  disnake/ext/tasks/__init__.py
  disnake/guild.py
  disnake/member.py
  disnake/utils.py
  requirements/requirements_dev.txt
  tests/test_utils.py
Labels: p: medium, s: needs review, t: meta

#595 feat: support additional union types for mentionable parameters
  disnake/ext/commands/params.py
  docs/ext/commands/slash_commands.rst
  tests/ext/commands/test_params.py
Labels: t: enhancement, p: low, s: needs review

#603 feat: add AllowedMentions.from_message
  disnake/mentions.py
  tests/test_mentions.py
Labels: t: enhancement, p: medium, s: needs review

#610 typing: use `typing_extensions.Self` instead of `TypeVar`s where applicable
  disnake/abc.py
  disnake/app_commands.py
  disnake/channel.py
  disnake/client.py
  disnake/colour.py
  disnake/components.py
  disnake/context_managers.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/core.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/flags.py
  disnake/gateway.py
  disnake/http.py
  disnake/interactions/application_command.py
  disnake/invite.py
  disnake/member.py
  disnake/mentions.py
  disnake/message.py
  disnake/partial_emoji.py
  disnake/permissions.py
  disnake/player.py
  disnake/role.py
  disnake/shard.py
  disnake/state.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
  disnake/user.py
  disnake/utils.py
Labels: p: low, s: needs review, t: refactor/typing/lint

#606 chore(lint): resolve some ignored flake8 errors
  .flake8
  disnake/abc.py
  disnake/audit_logs.py
  disnake/client.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  disnake/guild.py
  disnake/interactions/__init__.py
  disnake/invite.py
  disnake/iterators.py
  disnake/shard.py
  disnake/state.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
  disnake/utils.py
  disnake/voice_client.py
  disnake/webhook/__init__.py
Labels: p: medium, s: needs review, t: refactor/typing/lint

#620 Fix opus on macos arm64
  disnake/opus.py
Labels: t: bugfix

#605 feat: add more operators to flags
  changelog/605.feature.rst
  disnake/flags.py
  disnake/permissions.py
Labels: t: enhancement, p: medium, s: needs review

#629 ci: run check-pull-labels on synchronize
  .github/workflows/check-pull-labels.yaml
Labels: p: high, t: meta, t: bugfix, skip news

#628 feat: check for venv before installing dependencies in nox setup
  noxfile.py
Labels: t: enhancement, p: low, s: needs review, t: meta, skip news

#630 feat: add cancelled spelling to alias `GuildScheduledEventStatus.canceled`
  changelog/630.feature.rst
  disnake/enums.py
  docs/api.rst
Labels: t: enhancement, p: low

#624 typing(ui): add `slice` to `ActionRow.__getitem__` and `__delitem__` annotations
  changelog/624.misc.rst
  disnake/ui/action_row.py
Labels: p: low, s: needs review, t: refactor/typing/lint

#601 docs(contributing): explain how to write a pull
  CONTRIBUTING.md
  changelog/601.misc.rst
Labels: t: documentation, p: medium, s: needs review, t: meta

#528 feat: add nsfw field to application commands
  changelog/528.feature.rst
  disnake/app_commands.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  disnake/types/interactions.py
Labels: t: enhancement, t: api support, s: needs review

#639 fix(docs): float the footer when it clips the nav aside
  docs/_static/style.css
Labels: t: documentation, p: low, backport needed: 2.5, skip news

#418 refactor: improve channel edit typing
  changelog/418.bugfix.rst
  changelog/418.feature.rst
  changelog/418.misc.rst
  disnake/abc.py
  disnake/channel.py
  tests/test_abc.py
Labels: s: needs review, t: refactor/typing/lint

#625 docs: update `InteractionReference.name` description, now includes group and subcommand name
  changelog/625.doc.rst
  disnake/message.py
Labels: t: documentation, p: low, s: needs review

#637 fix: replace old command objects in cogs with new copies
  changelog/575.bugfix.rst
  disnake/ext/commands/cog.py
Labels: p: medium, s: needs review, backport needed: 2.5, t: bugfix

#645 docs(guild): fix grammatical errors in Guild channel properties
  changelog/645.doc.rst
  disnake/guild.py
Labels: t: documentation, p: low, s: needs review

#648 docs(message): remove duplicate line from `InteractionReference.name`
  changelog/648.doc.rst
  disnake/message.py
Labels: t: documentation, p: low, s: needs review, backport needed: 2.5

#646 fix(interactions): improve fallbacks in resolved data
  changelog/646.bugfix.rst
  disnake/interactions/application_command.py
Labels: s: needs review, backport needed: 2.5, t: bugfix

#632 docs: clarify partial returns for `Interaction.channel`
  changelog/632.doc.rst
  disnake/interactions/base.py
Labels: t: documentation, p: low, s: needs review

#281 button / select decorator support for Button & Select subclasses
  changelog/281.feature.rst
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select.py
  docs/api.rst
  tests/ui/test_decorators.py
Labels: t: enhancement, p: medium, s: needs review

#651 refactor: standardize id regex to {17,19}
  changelog/651.misc.rst
  disnake/ext/commands/converter.py
  disnake/ext/commands/help.py
  disnake/message.py
  disnake/partial_emoji.py
  disnake/utils.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: s: needs review, t: refactor/typing/lint

#642 feat: allow setting ChannelFlags directly when editing a channel or thread
  changelog/642.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/threads.py
Labels: t: enhancement, t: api support, p: medium, s: needs review

#530 feat: auto moderation
  changelog/530.feature.rst
  disnake/__init__.py
  disnake/audit_logs.py
  disnake/automod.py
  disnake/enums.py
  disnake/flags.py
  disnake/guild.py
  disnake/http.py
  disnake/iterators.py
  disnake/state.py
  disnake/types/audit_log.py
  disnake/types/automod.py
  disnake/types/guild.py
  docs/api.rst
  tests/test_flags.py
Labels: t: enhancement, t: api support, p: high, s: in progress, s: needs review

#609 tests: add tests for disnake/permissions.py
  disnake/permissions.py
  tests/test_permissions.py
Labels: p: medium, s: needs review, t: tests, skip news

#565 docs: update to sphinx 5.1
  changelog/565.doc.rst
  docs/_static/custom.js
  docs/_static/scorer.js
  docs/_static/searchtools.js
  docs/_static/style.css
  docs/conf.py
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  requirements/requirements_docs.txt
Labels: t: documentation, p: high, s: needs review, t: dependencies

#567 feat: Embed Limit Checks
  changelog/567.feature.rst
  disnake/embeds.py
  tests/test_embeds.py
Labels: t: enhancement, s: needs review

#615 feat: add ability to use more operators on flag values to create flag classes
  changelog/605.feature.rst
  changelog/615.feature.rst
  disnake/flags.py
  disnake/permissions.py
Labels: t: enhancement, s: needs review

#662 chore(docs): replace broken links and formatting in contributing documentation
  CONTRIBUTING.md
  changelog/README.rst
Labels: p: low, s: needs review, t: meta, skip news

#661 docs: add `i18n` documentation to subclasses of `disnake.Client`
  changelog/652.doc.rst
  disnake/ext/commands/bot.py
Labels: t: documentation, s: needs review

#636 docs: Add sidebar-navigable sub-sections to Event Reference section of API Reference documentation
  changelog/460.doc.rst
  docs/api.rst
Labels: t: documentation, s: needs review

#668 typing: update pyright, reconfigure rules
  disnake/activity.py
  disnake/components.py
  disnake/ext/commands/help.py
  disnake/http.py
  disnake/member.py
  disnake/partial_emoji.py
  pyproject.toml
  requirements/requirements_dev.txt
Labels: p: low, s: needs review, t: dependencies, t: meta, t: refactor/typing/lint, skip news

#667 chore: rename flag converter file to flag_converter to avoid conflicting with ext.commands flag classes
  changelog/667.misc.rst
  disnake/ext/commands/__init__.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/flag_converter.py
Labels: p: medium, s: needs review, t: bugfix

#660 refactor: remove fill_with_flags
  changelog/660.misc.rst
  disnake/flags.py
  disnake/permissions.py
  tests/test_flags.py
Labels: p: low, s: needs review, t: refactor/typing/lint
