Repository DisnakeDev/disnake, pull requests merged in 2022-11, with the labels that each got.

#842 release: 2.6.2
  changelog/818.bugfix.rst
  changelog/820.bugfix.rst
  changelog/825.bugfix.rst
  disnake/__init__.py
  docs/whats_new.rst
Labels: t: release

#843 docs: forward port the 2.6.2 changelog
  docs/whats_new.rst
Labels: t: documentation, skip news

#841 release: 2.7.0
  changelog/265.feature.rst
  changelog/393.doc.rst
  changelog/433.feature.rst
  changelog/468.feature.rst
  changelog/697.doc.rst
  changelog/764.doc.rst
  changelog/766.breaking.rst
  changelog/766.feature.rst
  changelog/777.bugfix.rst
  changelog/778.feature.rst
  changelog/781.feature.rst
  changelog/784.misc.0.rst
  changelog/784.misc.1.rst
  changelog/785.feature.rst
  changelog/786.doc.rst
  changelog/789.misc.rst
  changelog/791.feature.rst
  changelog/791.misc.rst
  changelog/792.bugfix.rst
  changelog/793.doc.rst
  changelog/797.doc.rst
  changelog/800.feature.rst
  changelog/803.feature.rst
  changelog/806.deprecate.rst
  changelog/806.feature.rst
  changelog/810.bugfix.rst
  changelog/814.breaking.rst
  changelog/814.bugfix.rst
  changelog/814.deprecate.rst
  changelog/816.feature.rst
  changelog/818.bugfix.rst
  changelog/820.bugfix.rst
  changelog/821.doc.rst
  changelog/822.feature.rst
  changelog/825.bugfix.rst
  changelog/827.bugfix.rst
  changelog/827.feature.rst
  changelog/829.feature.rst
  changelog/832.feature.rst
  changelog/833.feature.rst
  disnake/__init__.py
  docs/whats_new.rst
Labels: t: release

#844 bump to 2.8.0a
  disnake/__init__.py
Labels: s: needs review, skip news

#850 fix(ci): remove 3.11 alpha versions
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, skip news

#853 chore: update alls-green to fix ci deprecation warnings
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#830 build: declare a pep 517 compatible build backend
  .github/actions/setup-env/action.yml
  changelog/830.misc.rst
  pyproject.toml
  setup.py
Labels: t: enhancement, s: needs review, t: meta

#794 feat: support regex automod
  changelog/794.feature.rst
  disnake/automod.py
  disnake/types/automod.py
Labels: t: enhancement

#856 fix(ci): use `python -m pip`
  .github/actions/setup-env/action.yml
  .github/workflows/lint-test.yml
Labels: p: high, s: needs review, t: meta, t: bugfix, skip news

#866 feat(flags): add Active Developer flag
  changelog/866.feature.rst
  disnake/enums.py
  disnake/flags.py
  docs/api.rst
Labels: t: enhancement, t: api support

#869 chore: use bitshifting for all bitwise enums
  disnake/enums.py
Labels: t: enhancement, s: needs review, skip news

#872 docs: private threads no longer require boost/guild feature
  changelog/872.doc.rst
  disnake/channel.py
  disnake/guild.py
  disnake/threads.py
  disnake/types/guild.py
Labels: t: documentation, p: low, s: needs review

#859 docs: enable opensearch
  changelog/859.doc.rst
  docs/_templates/layout.html
  docs/conf.py
Labels: t: documentation, t: enhancement, p: low, s: needs review

#879 fix(channel): export ``ThreadWithMessage``
  changelog/879.bugfix.rst
  disnake/channel.py
Labels: s: needs review, t: bugfix, needs backport: 2.7
