Repository DisnakeDev/disnake, pull requests merged in 2022-10, with the labels that each got.

#784 fix: add missing py.typed markers to namespace packages
  MANIFEST.in
  changelog/784.misc.0.rst
  changelog/784.misc.1.rst
  disnake/ext/commands/py.typed
  disnake/ext/tasks/py.typed
Labels: t: refactor/typing/lint

#764 deps(docs): update sphinx to 5.2.3
  changelog/764.doc.rst
  docs/conf.py
  requirements/requirements_docs.txt
Labels: t: documentation, t: dependencies

#782 feat: hide the extra disnake.AutoShardedClient overload in typechecking
  disnake/shard.py
Labels: t: refactor/typing/lint, skip news

#789 feat: lessen the aiohttp dependency upper bound to allow up to v4.0
  changelog/789.misc.rst
  requirements.txt
Labels: t: dependencies

#790 feat: simplify branch protection by using a single check that affirms other jobs passed
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, skip news

#735 typing: use `typing_extensions.NotRequired` in `TypedDict`s
  disnake/types/activity.py
  disnake/types/appinfo.py
  disnake/types/audit_log.py
  disnake/types/automod.py
  disnake/types/channel.py
  disnake/types/components.py
  disnake/types/embed.py
  disnake/types/gateway.py
  disnake/types/guild.py
  disnake/types/guild_scheduled_event.py
  disnake/types/integration.py
  disnake/types/interactions.py
  disnake/types/invite.py
  disnake/types/member.py
  disnake/types/message.py
  disnake/types/role.py
  disnake/types/sticker.py
  disnake/types/threads.py
  disnake/types/voice.py
  disnake/types/webhook.py
Labels: p: low, s: needs review, t: refactor/typing/lint, skip news

#778 feat(codemod): fully type all flag classes' init methods
  changelog/778.feature.rst
  disnake/flags.py
  scripts/codemods/typed_flags.py
  scripts/codemods/typed_permissions.py
Labels: t: enhancement, s: needs review, t: refactor/typing/lint

#766 fix: update system_content with updated strings and always return str
  changelog/766.breaking.rst
  changelog/766.feature.rst
  disnake/message.py
Labels: breaking change, s: in progress, s: needs review

#781 feat(scheduled-events): add `start`, `end`, `cancel` shortcuts
  changelog/781.feature.rst
  disnake/guild.py
  disnake/guild_scheduled_event.py
Labels: t: enhancement, s: needs review

#793 docs: add Discord docs extlinks entry, update broken links
  changelog/793.doc.rst
  disnake/appinfo.py
  disnake/automod.py
  disnake/embeds.py
  disnake/guild.py
  disnake/raw_models.py
  disnake/types/activity.py
  disnake/types/gateway.py
  disnake/voice_client.py
  docs/api.rst
  docs/conf.py
Labels: t: documentation, p: low, s: needs review

#795 docs(automod): misc content fixes
  disnake/automod.py
  disnake/guild.py
Labels: t: documentation, s: needs review, skip news

#802 deps: update testing dependencies
  requirements/requirements_dev.txt
Labels: s: needs review, t: dependencies, skip news

#792 fix: ensure embed fields are copied properly
  changelog/792.bugfix.rst
  disnake/embeds.py
  tests/test_embeds.py
Labels: s: needs review, t: bugfix, needs backport: 2.6

#800 refactor: split select menu types into base and concrete type
  .flake8
  changelog/800.feature.rst
  disnake/components.py
  disnake/interactions/message.py
  disnake/types/components.py
  disnake/ui/action_row.py
  disnake/ui/item.py
  disnake/ui/select/__init__.py
  disnake/ui/select/base.py
  disnake/ui/select/string.py
  docs/api.rst
  setup.py
Labels: p: high, s: needs review, t: refactor/typing/lint

#697 docs: split changelog to current and legacy versions
  changelog/697.doc.rst
  docs/conf.py
  docs/index.rst
  docs/migrating.rst
  docs/whats_new.rst
  docs/whats_new_legacy.rst
Labels: t: documentation, p: low, s: needs review

#801 typing: misc internal component typing changes
  disnake/components.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/select/string.py
  disnake/ui/view.py
  disnake/utils.py
Labels: s: needs review, t: refactor/typing/lint, skip news

#805 docs: remove parameters that were documented on the wrong class
  disnake/client.py
Labels: t: documentation, s: needs review, skip news

#797 docs: custom 404 page
  changelog/797.doc.rst
  docs/404.rst
  docs/conf.py
  requirements/requirements_docs.txt
Labels: t: documentation, s: needs review

#809 docs: fix spacing issue due to the reordering of material icons css
  docs/_templates/layout.html
Labels: t: documentation, skip news

#810 fix: don't provide a default clean history duration as that makes the delete_message_days parameter unusable
  changelog/810.bugfix.rst
  disnake/member.py
Labels: p: medium, t: bugfix, needs backport: 2.6

#812 backport(2.6): don't provide a default clean history duration in `Member.ban`
  changelog/810.bugfix.rst
  disnake/member.py
Labels: s: needs review, backport: 2.6

#811 backport(2.6): ensure embed fields are copied properly
  changelog/792.bugfix.rst
  disnake/embeds.py
  tests/test_embeds.py
Labels: backport: 2.6

#813 release: 2.6.1
  changelog/792.bugfix.rst
  changelog/810.bugfix.rst
  disnake/__init__.py
  docs/whats_new.rst
Labels: t: release

#817 ci: update actions/packages to avoid deprecation warnings
  .github/actions/setup-env/action.yml
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, skip news

#791 feat(cli): improve the experience by providing help by default and allowing InteractionBot to be used
  changelog/791.feature.rst
  changelog/791.misc.rst
  disnake/__main__.py
Labels: t: enhancement, s: needs review

#816 feat: support `delete_after` for ephemeral messages
  changelog/816.feature.rst
  disnake/interactions/base.py
  disnake/webhook/async_.py
Labels: t: enhancement, t: api support, s: needs review

#820 fix: fix off-by-one error in `AutoModKeywordPresets`
  changelog/820.bugfix.rst
  disnake/flags.py
Labels: s: needs review, t: bugfix, needs backport: 2.6

#393 docs: use lazy hoverxref
  changelog/393.doc.rst
  docs/_static/custom.js
  docs/conf.py
  requirements/requirements_docs.txt
Labels: t: documentation

#818 fix: only send `rate_limit_per_user` parameter on thread creation if required
  changelog/818.bugfix.rst
  disnake/channel.py
  disnake/http.py
  disnake/message.py
Labels: p: medium, s: needs review, t: bugfix, needs backport: 2.6

#822 feat: make `slowmode_delay` parameter of `ForumChannel.create_thread` optional
  changelog/822.feature.rst
  disnake/channel.py
Labels: t: enhancement, p: low, s: needs review

#825 fix: optional variadic arguments no longer can be stuck in infinite loops
  changelog/825.bugfix.rst
  disnake/ext/commands/core.py
Labels: p: high, t: bugfix, backport: 2.6

#788 docs: show hoverxref for intersphinx projects
  docs/conf.py
  docs/faq.rst
  requirements/requirements_docs.txt
Labels: t: documentation

#814 refactor: slightly rework resolved interaction data handling
  changelog/814.breaking.rst
  changelog/814.bugfix.rst
  changelog/814.deprecate.rst
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/types/interactions.py
  docs/api.rst
  tests/interactions/test_base.py
Labels: s: needs review, t: refactor/typing/lint, t: deprecation, t: bugfix

#806 feat: new command sync options
  changelog/265.feature.rst
  changelog/433.feature.rst
  changelog/468.feature.rst
  changelog/806.deprecate.rst
  changelog/806.feature.rst
  disnake/ext/commands/__init__.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/interaction_bot_base.py
  docs/ext/commands/additional_info.rst
  docs/ext/commands/api.rst
  docs/ext/commands/slash_commands.rst
  scripts/codemods/typed_flags.py
  test_bot/__main__.py
Labels: t: enhancement, p: high, t: deprecation

#824 tests: add basic command view tests
  tests/ext/commands/test_view.py
Labels: t: tests, skip news

#832 feat: allow suppressing embeds when editing an interaction response
  changelog/832.feature.rst
  disnake/interactions/base.py
Labels: t: enhancement, t: api support, s: needs review

#827 fix: silence python3.11 asyncio deprecation warnings
  changelog/827.bugfix.rst
  disnake/client.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/tasks/__init__.py
  disnake/http.py
  disnake/player.py
  disnake/ui/modal.py
Labels: p: high, s: needs review

#833 feat: add `_MissingSentinel.__hash__`
  disnake/ext/commands/flag_converter.py
  disnake/utils.py
Labels: t: enhancement, s: needs review, skip news

#835 docs: forward port v2.6.1 changelog
  docs/whats_new.rst
Labels: t: documentation, s: needs review

#838 fix(ci): indent quoted multiline string
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, needs backport: 2.5, t: bugfix, skip news, needs backport: 2.6

#786 docs: clarify `disnake.Embed` re-using `disnake.File` objects when editing messages
  changelog/786.doc.rst
  disnake/embeds.py
  disnake/file.py
Labels: t: documentation, s: needs review

#834 docs: unify description for `suppress_embeds` across all files
  disnake/abc.py
  disnake/channel.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: documentation, s: needs review, skip news

#829 feat: officially support python 3.11
  .github/workflows/lint-test.yml
  changelog/785.feature.rst
  changelog/827.feature.rst
  changelog/829.feature.rst
  changelog/833.feature.rst
  setup.py
Labels: p: high, t: meta

#840 backport(6c69226a): fix(ci): indent quoted multiline string
  .github/workflows/lint-test.yml
Labels: p: high, skip news, backport: 2.6
