Repository DisnakeDev/disnake, pull requests merged in 2023-03, with the labels that each got.

#965 chore: add py3.11 to local nox testing
  noxfile.py
  pyproject.toml
Labels: s: needs review, t: meta, skip news

#966 chore: update dev dependencies
  pyproject.toml
Labels: s: needs review, t: dependencies, skip news

#967 fix: use correct packet sizes for voice IP discovery
  changelog/967.bugfix.rst
  disnake/gateway.py
Labels: p: high, s: needs review, t: bugfix, needs backport: 2.7, needs backport: 2.8

#961 lint: enable more pydocstyle rules
  changelog/961.doc.rst
  disnake/abc.py
  disnake/asset.py
  disnake/automod.py
  disnake/channel.py
  disnake/client.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/i18n.py
  disnake/interactions/application_command.py
  disnake/iterators.py
  disnake/player.py
  disnake/reaction.py
  disnake/threads.py
  disnake/utils.py
  disnake/voice_client.py
  examples/secret.py
  pyproject.toml
  test_bot/cogs/injections.py
  test_bot/cogs/slash_commands.py
  tests/test_utils.py
Labels: t: documentation, t: refactor/typing/lint, skip news

#968 chore(deps): allow PyNaCl 1.5 to be used
  changelog/968.misc.rst
  pyproject.toml
Labels: s: needs review, t: dependencies

#963 docs: add searching within sidebar
  changelog/963.doc.rst
  docs/_static/sidebar.js
  docs/_static/style.css
  docs/_templates/layout.html
Labels: t: documentation, t: enhancement

#958 chore(lint): add autotyping for automatic typing of known types
  .github/workflows/lint-test.yml
  .libcst.codemod.yaml
  disnake/__main__.py
  disnake/abc.py
  disnake/enums.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/help.py
  disnake/ext/commands/view.py
  disnake/flags.py
  disnake/guild.py
  disnake/iterators.py
  disnake/player.py
  disnake/voice_client.py
  noxfile.py
  pyproject.toml
  test_bot/__init__.py
  test_bot/__main__.py
  test_bot/cogs/events.py
  test_bot/cogs/guild_scheduled_events.py
  test_bot/cogs/injections.py
  test_bot/cogs/localization.py
  test_bot/cogs/message_commands.py
  test_bot/cogs/misc.py
  test_bot/cogs/slash_commands.py
  test_bot/cogs/user_commands.py
  tests/ext/commands/test_base_core.py
  tests/ext/commands/test_core.py
  tests/ext/commands/test_slash_core.py
  tests/ext/commands/test_view.py
  tests/ext/tasks/test_loops.py
  tests/helpers.py
  tests/interactions/test_base.py
  tests/test_colour.py
  tests/test_http.py
  tests/test_message.py
  tests/test_object.py
  tests/test_permissions.py
  tests/test_utils.py
  tests/ui/test_action_row.py
  tests/ui/test_decorators.py
Labels: s: needs review, t: refactor/typing/lint, skip news

#862 fix(voice): send speaking packet on reconnect
  changelog/845.bugfix.rst
  disnake/gateway.py
  disnake/player.py
Labels: s: needs review, t: bugfix, needs backport: 2.7, needs backport: 2.8

#970 docs: forward-port 2.7.2/2.8.1 changelogs
  docs/whats_new.rst
Labels: t: documentation, t: release, skip news

#974 fix: member not being cached in `Guild.getch_members` in the case of `user_ids` of length one
  changelog/974.bugfix.rst
  disnake/guild.py
Labels: p: low, s: needs review, t: bugfix

#950 refactor(lint): add flake8-raises
  changelog/950.feature.rst
  disnake/abc.py
  disnake/embeds.py
  disnake/enums.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/commands/flag_converter.py
  disnake/ext/tasks/__init__.py
  disnake/http.py
  disnake/iterators.py
  disnake/opus.py
  disnake/threads.py
  disnake/utils.py
  pyproject.toml
Labels: s: needs review, t: refactor/typing/lint

#946 fix: copy `ParamInfo` instances from signatures before processing them
  changelog/946.bugfix.rst
  disnake/ext/commands/params.py
  disnake/i18n.py
Labels: p: low, s: needs review, t: bugfix

#978 fix(ci): avoid installing dependencies outside of venv for pyright
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, skip news

#979 feat(bot): add a new `get_listeners` method
  changelog/976.feature.rst
  disnake/ext/commands/common_bot_base.py
Labels: t: enhancement, s: needs review

#969 ci: use the native libcst parser
  noxfile.py
Labels: s: needs review, t: meta, skip news

#971 fix(nox): always run autotyping from codemod session, set `--hide-progress` consistently
  noxfile.py
Labels: s: needs review, t: meta, t: bugfix, skip news

#985 deps: update ruff to 0.0.257
  .pre-commit-config.yaml
  disnake/client.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/common_bot_base.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/guild.py
  disnake/http.py
  disnake/opus.py
  disnake/voice_client.py
  noxfile.py
  pyproject.toml
Labels: t: dependencies, skip news
