Repository DisnakeDev/disnake, pull requests merged in 2023-08, with the labels that each got.

#1080 feat(auditlog): add creator monetization action types
  changelog/1080.feature.rst
  disnake/enums.py
  disnake/types/audit_log.py
  docs/api/audit_logs.rst
Labels: t: enhancement, t: api support, s: needs review

#1078 feat(channel): add `default_layout` parameter to `create_forum_channel`
  changelog/1078.feature.rst
  disnake/channel.py
  disnake/guild.py
  disnake/http.py
Labels: t: enhancement, t: api support, s: needs review

#1089 docs: clarify `Guild.fetch_member` raised exceptions
  .gitignore
  disnake/client.py
  disnake/guild.py
Labels: t: documentation, skip news

#687 feat(activity): improve custom asset image support
  changelog/687.feature.0.rst
  changelog/687.feature.1.rst
  disnake/activity.py
  docs/api/activities.rst
  tests/test_activity.py
Labels: t: enhancement, t: api support, p: low, s: needs review

#1067 feat(commands.cog): pass errors raised by cog_unload to the bot's on_error
  changelog/1046.feature.rst
  disnake/ext/commands/cog.py
Labels: t: enhancement, s: needs review

#1066 feat(client): implement a listener system for disnake.Client
  changelog/975.feature.rst
  disnake/client.py
  disnake/ext/commands/common_bot_base.py
  docs/api/clients.rst
  docs/api/events.rst
  docs/ext/commands/api/bots.rst
  tests/test_events.py
Labels: t: enhancement, s: needs review, t: refactor/typing/lint

#1093 fix: don't pop key in `MessageReference.with_state`
  disnake/message.py
  disnake/types/message.py
Labels: t: bugfix, skip news, needs backport: 2.9

#1082 fix: standard stickers no longer require nitro
  changelog/1082.deprecate.rst
  disnake/client.py
  disnake/http.py
  disnake/sticker.py
  disnake/types/sticker.py
  docs/api/stickers.rst
Labels: t: documentation, t: deprecation, t: bugfix

#1087 feat(activity): fall back to `name` for custom activities
  changelog/1087.feature.rst
  disnake/activity.py
  docs/faq.rst
Labels: t: enhancement, s: needs review

#1097 chore(testbot): refactor error handling into one common handler
  test_bot/__main__.py
Labels: t: refactor/typing/lint, t: bugfix, skip news

#808 feat(cli): add all missing cog special methods
  changelog/808.misc.rst
  disnake/__main__.py
Labels: t: enhancement, s: needs review

#1092 ci: add pr title validator
  .github/workflows/semantic-pr-title.yml
Labels: s: needs review, t: meta, skip news
