Repository DisnakeDev/disnake, pull requests merged in 2023-11, with the labels that each got.

#1131 docs: add v2.9.1 changelog to latest docs
  docs/whats_new.rst
Labels: t: documentation

#1048 fix(commands): Fix application command checks' typing
  changelog/1045.bugfix.rst
  changelog/1045.feature.rst
  disnake/ext/commands/_types.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/core.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/interaction_bot_base.py
  docs/ext/commands/api/checks.rst
Labels: s: needs review, t: refactor/typing/lint

#847 feat: don't parse self/ctx parameter annotations of prefix command callbacks
  changelog/847.feature.rst
  disnake/ext/commands/core.py
  disnake/ext/commands/help.py
  disnake/ext/commands/params.py
  disnake/utils.py
  tests/ext/commands/test_params.py
  tests/test_utils.py
Labels: t: enhancement, s: needs review, t: bugfix

#1122 build(deps): update pyright to v1.1.336
  disnake/abc.py
  disnake/activity.py
  disnake/asset.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/client.py
  disnake/components.py
  disnake/emoji.py
  disnake/enums.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/cooldowns.py
  disnake/ext/commands/core.py
  disnake/ext/commands/help.py
  disnake/ext/commands/params.py
  disnake/ext/commands/slash_core.py
  disnake/ext/tasks/__init__.py
  disnake/gateway.py
  disnake/guild.py
  disnake/http.py
  disnake/i18n.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/message.py
  disnake/shard.py
  disnake/state.py
  disnake/types/audit_log.py
  disnake/types/automod.py
  disnake/types/template.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/modal.py
  disnake/ui/select/channel.py
  disnake/ui/select/mentionable.py
  disnake/ui/select/role.py
  disnake/ui/select/string.py
  disnake/ui/select/user.py
  disnake/utils.py
  disnake/voice_client.py
  docs/extensions/builder.py
  examples/basic_voice.py
  examples/interactions/injections.py
  examples/interactions/modal.py
  pyproject.toml
  test_bot/cogs/modals.py
  tests/ui/test_decorators.py
Labels: s: needs review, t: dependencies, t: refactor/typing/lint, skip news

#1094 feat: add `TeamMember.role`
  changelog/1094.doc.rst
  changelog/1094.feature.0.rst
  changelog/1094.feature.1.rst
  disnake/enums.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/common_bot_base.py
  disnake/team.py
  disnake/types/team.py
  docs/api/app_info.rst
Labels: t: enhancement, t: api support, s: needs review

#1091 feat(permissions): add `create_guild_expressions` and `create_events` perms
  changelog/1091.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/emoji.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/permissions.py
  disnake/sticker.py
Labels: t: enhancement, t: api support, s: needs review

#1112 docs: adds docstrings for some properties of `InvokableSlashCommand` and `SubCommand` and document `Option`'s attributes
  changelog/1112.doc.rst
  disnake/app_commands.py
  disnake/ext/commands/slash_core.py
  docs/api/app_commands.rst
Labels: t: documentation, s: needs review

#1136 fix(appcmd): use covariant collection types for `choices`
  changelog/1136.bugfix.rst
  disnake/app_commands.py
  disnake/ext/commands/params.py
  disnake/interactions/base.py
Labels: t: enhancement, s: needs review, t: bugfix, needs backport: 2.9
