Repository DisnakeDev/disnake, pull requests merged in 2023-09, with the labels that each got.

#1037 feat(typing): make `Interaction` and subclasses generic
  changelog/1036.feature.rst
  disnake/ext/commands/params.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/ui/item.py
  disnake/ui/modal.py
  disnake/utils.py
  examples/interactions/converters.py
  examples/interactions/param.py
  test_bot/cogs/guild_scheduled_events.py
  test_bot/cogs/injections.py
  test_bot/cogs/localization.py
  test_bot/cogs/message_commands.py
  test_bot/cogs/misc.py
  test_bot/cogs/modals.py
  test_bot/cogs/slash_commands.py
  test_bot/cogs/user_commands.py
Labels: s: needs review, t: refactor/typing/lint

#1098 docs: rewrite CONTRIBUTING.md
  CONTRIBUTING.md
  changelog/1098.misc.rst
Labels: t: documentation, s: needs review, t: meta

#1096 feat(auditlog): support `integration_type` field
  changelog/1096.feature.rst
  disnake/audit_logs.py
  disnake/types/audit_log.py
  docs/api/audit_logs.rst
Labels: t: enhancement, t: api support, s: needs review

#1105 docs(audit_logs): misc typo/formatting fixes
  changelog/1105.doc.rst
  disnake/audit_logs.py
  docs/api/audit_logs.rst
Labels: t: documentation, needs backport: 2.9

#1095 feat: add `created_at` to more models
  changelog/1095.feature.rst
  disnake/automod.py
  disnake/integrations.py
  disnake/stage_instance.py
  disnake/team.py
  disnake/threads.py
Labels: t: enhancement, p: low, s: needs review

#1109 refactor: deduplicate `owner_ids` logic
  disnake/ext/commands/bot.py
  disnake/ext/commands/common_bot_base.py
Labels: s: needs review, t: refactor/typing/lint, skip news

#1110 ci: print libcst diff
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#882 feat(StageInstance): add `guild_scheduled_event` field to create instance
  changelog/882.feature.rst
  disnake/channel.py
  disnake/http.py
Labels: t: enhancement, t: api support, s: needs review
