Repository DisnakeDev/disnake, pull requests merged in 2023-06, with the labels that each got.

#837 feat: add missing kwargs and clone all settable attributes in all `Channel.clone()` methods
  changelog/635.bugfix.rst
  changelog/635.feature.rst
  disnake/abc.py
  disnake/channel.py
Labels: t: enhancement, s: needs review, t: bugfix

#1013 fix: don't require `Intents.members` for `Guild.fetch_members`
  changelog/1013.bugfix.rst
  disnake/guild.py
Labels: p: low, s: needs review, t: bugfix

#1040 feat: support `animated` field for emojis in reaction remove events
  changelog/1040.feature.rst
  disnake/raw_models.py
  disnake/state.py
Labels: t: enhancement, t: api support, s: needs review

#1041 feat: voice messages
  changelog/1041.feature.rst
  disnake/flags.py
  disnake/message.py
  disnake/types/message.py
Labels: t: enhancement, t: api support, s: needs review

#1035 fix(enum): deprecates Party Type enum (#1023)
  changelog/1035.deprecate.rst
  disnake/abc.py
Labels: s: needs review, t: deprecation

#1009 fix(auditlog): support threads in `extra` attribute
  changelog/1009.bugfix.rst
  disnake/audit_logs.py
  docs/api/audit_logs.rst
Labels: s: needs review, t: bugfix

#1057 docs: add links to version guarantees and whatsnew on both pages
  docs/version_guarantees.rst
  docs/whats_new.rst
Labels: t: documentation, s: needs review, skip news

#1054 build(deps): bump sphinx to 7.0.1
  pyproject.toml
Labels: s: needs review, t: dependencies, skip news

#1056 docs: add disclaimer about creating >30d invites
  changelog/1056.doc.rst
  disnake/abc.py
Labels: t: documentation, s: needs review

#863 fix(voice): stop websocket heartbeat on close
  changelog/863.bugfix.rst
  disnake/voice_client.py
Labels: p: low, s: needs review, t: bugfix

#1055 build(deps): bump towncrier to 23.6.0
  pyproject.toml
Labels: s: needs review, t: dependencies, skip news

#1051 typing: fix `abc.User` protocol structural subtyping
  changelog/1051.bugfix.rst
  disnake/abc.py
  disnake/member.py
  tests/test_abc.py
Labels: s: needs review, t: refactor/typing/lint

#1047 fix: show the proper permissions in threads
  changelog/1047.bugfix.rst
  disnake/abc.py
  disnake/channel.py
  disnake/threads.py
Labels: s: needs review, t: bugfix

#1059 fix(params): avoid calling `signature()` twice
  disnake/ext/commands/params.py
Labels: s: needs review, t: refactor/typing/lint, t: bugfix, skip news

#991 refactor(ext.commands): completely rewrite `Range` and `String`, require type argument
  changelog/991.bugfix.rst
  changelog/991.deprecate.0.rst
  changelog/991.deprecate.1.rst
  disnake/ext/commands/params.py
  disnake/ext/mypy_plugin/__init__.py
  docs/ext/commands/slash_commands.rst
  examples/interactions/param.py
  test_bot/cogs/slash_commands.py
  tests/ext/commands/test_params.py
Labels: p: medium, s: needs review, t: deprecation, t: bugfix

#1052 docs: misc fixes/clarifications
  changelog/635.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/client.py
  docs/api/events.rst
Labels: t: documentation, skip news

#1061 chore: update dev version to 2.10a
  disnake/__init__.py
Labels: t: meta, skip news

#1063 docs: clarify `Member.current_timeout` expiry
  disnake/member.py
Labels: t: documentation, skip news, needs backport: 2.9
