Repository DisnakeDev/disnake, pull requests merged in 2023-10, with the labels that each got.

#1000 build(deps): update black to v23.9.1
  .pre-commit-config.yaml
  pyproject.toml
Labels: t: dependencies, skip news

#1102 feat(colour): update and add new theme color values
  changelog/1102.bugfix.rst
  changelog/1102.feature.rst
  disnake/colour.py
Labels: t: enhancement, t: bugfix

#1119 build(deps): update ruff to v0.0.292
  .pre-commit-config.yaml
  disnake/enums.py
  disnake/errors.py
  disnake/ext/commands/context.py
  disnake/ext/commands/help.py
  disnake/opus.py
  disnake/utils.py
  docs/extensions/attributetable.py
  pyproject.toml
  tests/test_utils.py
Labels: t: dependencies, skip news

#1117 ci: start testing with python 3.12
  .github/workflows/lint-test.yml
  changelog/1117.misc.rst
  noxfile.py
  pyproject.toml
Labels: t: enhancement, s: needs review, t: meta

#1124 fix(threads): move runtime import required for `Thread.permissions_for`
  changelog/1123.bugfix.rst
  disnake/threads.py
Labels: t: bugfix, needs backport: 2.9

#1120 fix(commands): resolve unstringified annotation before caching
  changelog/1120.bugfix.rst
  disnake/utils.py
  tests/test_utils.py
Labels: t: bugfix, needs backport: 2.9

#1125 feat(lint): enable ruff `TCH` (flake8-type-checking) rules
  disnake/ext/commands/common_bot_base.py
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  docs/extensions/exception_hierarchy.py
  docs/extensions/fulltoc.py
  docs/extensions/nitpick_file_ignorer.py
  docs/extensions/redirects.py
  docs/extensions/resourcelinks.py
  pyproject.toml
  tests/ext/commands/test_core.py
  tests/helpers.py
  tests/ui/test_action_row.py
Labels: t: enhancement, t: refactor/typing/lint, skip news

#1126 docs: make `Supported Operations` container collapsible
  changelog/1126.doc.rst
  disnake/activity.py
  disnake/asset.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/colour.py
  disnake/embeds.py
  disnake/emoji.py
  disnake/ext/commands/flag_converter.py
  disnake/ext/commands/flags.py
  disnake/ext/commands/help.py
  disnake/flags.py
  disnake/guild.py
  disnake/guild_scheduled_event.py
  disnake/invite.py
  disnake/member.py
  disnake/message.py
  disnake/object.py
  disnake/partial_emoji.py
  disnake/permissions.py
  disnake/reaction.py
  disnake/role.py
  disnake/stage_instance.py
  disnake/sticker.py
  disnake/team.py
  disnake/threads.py
  disnake/ui/action_row.py
  disnake/user.py
  disnake/voice_region.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  disnake/widget.py
  docs/_static/style.css
  docs/api/audit_logs.rst
  docs/api/guilds.rst
  docs/api/messages.rst
  docs/api/misc.rst
  docs/conf.py
  docs/extensions/collapse.py
Labels: t: documentation, s: needs review

#1121 fix(commands): handle interactions in union types correctly
  changelog/1121.feature.rst
  disnake/ext/commands/params.py
  tests/ext/commands/test_params.py
Labels: t: bugfix

#1116 refactor: unify slash/prefix command signature evaluation
  changelog/1116.misc.rst
  disnake/ext/commands/core.py
  disnake/ext/commands/params.py
  disnake/utils.py
  tests/ext/commands/test_params.py
Labels: s: needs review, t: refactor/typing/lint

#1111 fix(ui): don't require `cls` argument in select decorators to be positional
  changelog/1111.bugfix.rst
  disnake/ui/button.py
  disnake/ui/select/channel.py
  disnake/ui/select/mentionable.py
  disnake/ui/select/role.py
  disnake/ui/select/string.py
  disnake/ui/select/user.py
  docs/api/ui.rst
  tests/ui/test_decorators.py
Labels: s: needs review, t: bugfix, needs backport: 2.9

#1072 feat(ci): automated release workflow
  .github/CODEOWNERS
  .github/workflows/build-release.yaml
  .github/workflows/changelog.yaml
  .github/workflows/create-release-pr.yaml
  .github/workflows/lint-test.yml
  .pre-commit-config.yaml
  RELEASE.md
  disnake/__init__.py
  pyproject.toml
  scripts/ci/versiontool.py
Labels: s: needs review, t: meta, skip news, needs backport: 2.9
