Repository DisnakeDev/disnake, pull requests merged in 2023-04, with the labels that each got.

#988 feat(ApplicationFlags): add `application_auto_moderation_rule_create_badge`
  changelog/988.feature.rst
  disnake/flags.py
Labels: t: enhancement, t: api support, s: needs review

#741 feat: add Guild.max_stage_video_channel_users
  changelog/741.feature.rst
  disnake/guild.py
  disnake/types/guild.py
Labels: t: enhancement, t: api support

#986 chore: deprecate/remove `AutoModTriggerType.harmful_link`
  changelog/986.deprecate.rst
  disnake/enums.py
  docs/api.rst
Labels: t: api support, s: needs review, t: deprecation

#990 fix!: remove `utils.parse_token`
  changelog/990.misc.rst
  disnake/utils.py
  tests/test_utils.py
Labels: breaking change, s: needs review, t: bugfix

#996 fix(typing): update misc payload types
  changelog/996.bugfix.rst
  changelog/996.misc.rst
  disnake/sticker.py
  disnake/types/message.py
  disnake/types/sticker.py
  disnake/types/team.py
Labels: s: needs review, t: refactor/typing/lint, t: bugfix, needs backport: 2.8

#1001 refactor(permissions): use the typed update method for all_channel()
  disnake/permissions.py
Labels: p: low, s: needs review, t: refactor/typing/lint, skip news

#999 chore(deps): update ruff to 0.0.261
  .pre-commit-config.yaml
  disnake/ext/commands/context.py
  pyproject.toml
  tests/test_embeds.py
  tests/ui/test_action_row.py
Labels: s: needs review, t: dependencies, t: refactor/typing/lint, skip news

#980 refactor: move/rename internal emoji methods
  disnake/audit_logs.py
  disnake/channel.py
  disnake/partial_emoji.py
  disnake/reaction.py
  disnake/state.py
  disnake/threads.py
  disnake/welcome_screen.py
Labels: s: needs review, t: refactor/typing/lint, skip news

#1005 chore: update default `Guild.filesize_limit` to 26214400 (25MB)
  changelog/1005.misc.rst
  disnake/guild.py
Labels: t: api support, s: needs review, needs backport: 2.8

#928 feat: implement onboarding
  changelog/928.feature.rst
  disnake/__init__.py
  disnake/enums.py
  disnake/guild.py
  disnake/http.py
  disnake/onboarding.py
  disnake/types/onboarding.py
  docs/api/guilds.rst
  tests/test_onboarding.py
Labels: t: enhancement, t: api support, s: needs review

#995 fix(auditlog): handle `options.channel_id` null value
  changelog/995.bugfix.rst
  disnake/audit_logs.py
  disnake/types/audit_log.py
  docs/api/audit_logs.rst
Labels: s: needs review, t: bugfix, needs backport: 2.8

#1019 docs: sort event categories alphabetically
  docs/api/events.rst
Labels: t: documentation, skip news
