Repository DisnakeDev/disnake, pull requests merged in 2023-07, with the labels that each got.

#1053 perf: optimize codemod performance, trim unused libcst features
  noxfile.py
  pyproject.toml
  scripts/codemods/base.py
  scripts/codemods/combined.py
  scripts/codemods/overloads_no_missing.py
  scripts/codemods/typed_flags.py
  scripts/codemods/typed_permissions.py
Labels: t: enhancement, s: needs review, t: meta, skip news

#1071 add intents definition to minimal bot example
  docs/intro.rst
  docs/quickstart.rst
Labels: t: documentation, skip news

#1074 fix(codemod): reinstate context module reference
  scripts/codemods/base.py
Labels: t: meta, t: bugfix, skip news

#1070 ci: remove coveralls
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#892 feat(GuildIterator): fill `approximate_member_count` and `approximate_presence_count` fields when fetching Guilds
  changelog/892.feature.rst
  disnake/client.py
  disnake/http.py
  disnake/iterators.py
Labels: t: enhancement, t: api support, s: needs review

#1076 chore(i18n): Include failed key in localization warnings
  disnake/i18n.py
Labels: t: enhancement, s: needs review, skip news

#1014 feat(interactions): support `delete_after` for edits
  changelog/1014.feature.rst
  disnake/interactions/base.py
Labels: t: enhancement, p: low, s: needs review

#1075 docs: fix and clarify the docs of SyncWebhook.from_url and SyncWebhook.partial
  disnake/webhook/sync.py
Labels: t: documentation, s: needs review, skip news

#1069 feat: role flags
  changelog/1069.feature.rst
  disnake/flags.py
  disnake/http.py
  disnake/role.py
  disnake/types/role.py
  docs/api/roles.rst
Labels: t: enhancement, t: api support, s: needs review

#1073 feat: attachment flags
  changelog/1073.feature.rst
  disnake/flags.py
  disnake/message.py
  disnake/types/message.py
  docs/api/messages.rst
Labels: t: enhancement, t: api support, s: needs review
