Repository DisnakeDev/disnake, pull requests merged in 2023-02, with the labels that each got.

#923 docs: fix missing spaces in `ApplicationRoleConnectionMetadataType` enum
  docs/api.rst
Labels: t: documentation, skip news

#924 fix wording of 'on_guild_role_create/delete'
  docs/api.rst
Labels: t: documentation, skip news

#920 feat: add fallback to `Object` for user property in AuditLogEntry
  changelog/920.feature.rst
  disnake/audit_logs.py
Labels: t: enhancement, s: needs review

#902 feat(enums): adds support for events enums
  changelog/895.feature.rst
  disnake/client.py
  disnake/enums.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/common_bot_base.py
  docs/api.rst
Labels: t: enhancement, s: needs review, t: refactor/typing/lint

#921 ci: update `pre-commit/action` and `isort`
  .github/workflows/lint-test.yml
  .pre-commit-config.yaml
Labels: s: needs review, t: dependencies, t: meta, skip news

#915 feat: add support for `GUILD_AUDIT_LOG_ENTRY_CREATE` event
  changelog/915.feature.rst
  disnake/audit_logs.py
  disnake/enums.py
  disnake/flags.py
  disnake/state.py
  disnake/types/gateway.py
  docs/api.rst
  docs/faq.rst
  docs/locale/ja/LC_MESSAGES/api.po
Labels: t: enhancement, t: api support, s: needs review

#912 fix!: `StickerPack.cover_sticker_id` and `.banner_asset_id` are optional
  changelog/912.breaking.rst
  changelog/912.bugfix.rst
  disnake/sticker.py
  disnake/types/sticker.py
Labels: breaking change, p: medium, s: needs review, t: bugfix

#922 fix: use `errno.ECONNRESET` to handle connection resets on Linux properly
  changelog/921.bugfix.rst
  disnake/client.py
  disnake/http.py
  disnake/shard.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: p: low, s: needs review, t: bugfix

#925 release: v2.8.0
  changelog/578.feature.rst
  changelog/794.feature.rst
  changelog/830.misc.rst
  changelog/839.feature.rst
  changelog/849.bugfix.rst
  changelog/854.feature.rst
  changelog/858.bugfix.rst
  changelog/859.doc.rst
  changelog/864.doc.rst
  changelog/865.feature.rst
  changelog/866.feature.rst
  changelog/870.bugfix.rst
  changelog/872.doc.rst
  changelog/873.feature.rst
  changelog/877.doc.rst
  changelog/877.feature.rst
  changelog/879.bugfix.rst
  changelog/880.bugfix.rst
  changelog/883.feature.rst
  changelog/885.feature.rst
  changelog/887.bugfix.rst
  changelog/890.feature.rst
  changelog/895.feature.rst
  changelog/903.feature.rst
  changelog/905.feature.rst
  changelog/906.feature.rst
  changelog/907.bugfix.rst
  changelog/910.feature.rst
  changelog/911.bugfix.rst
  changelog/912.breaking.rst
  changelog/912.bugfix.rst
  changelog/915.feature.rst
  changelog/918.feature.rst
  changelog/920.feature.rst
  changelog/921.bugfix.rst
  disnake/__init__.py
  docs/whats_new.rst
Labels: t: release

#926 chore: bump to 2.9.0a
  disnake/__init__.py
Labels: t: meta, skip news

#931 docs: update automod rule limits
  changelog/931.doc.rst
  disnake/automod.py
Labels: t: documentation, t: api support, s: needs review

#930 deps: update pyright to v1.1.291
  disnake/components.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/core.py
  disnake/ext/tasks/__init__.py
  disnake/interactions/base.py
  requirements/requirements_dev.txt
Labels: s: needs review, t: dependencies, skip news

#932 deps: update black to 23.1.0
  .pre-commit-config.yaml
  disnake/ext/commands/bot.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/guild.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/player.py
  disnake/types/gateway.py
  disnake/types/interactions.py
  disnake/ui/view.py
  disnake/welcome_screen.py
  docs/extensions/attributetable.py
  examples/interactions/param.py
  requirements/requirements_tools.txt
  scripts/codemods/typed_flags.py
  tests/ext/commands/test_view.py
Labels: t: dependencies, skip news

#851 fix(ci): move concurrency rules from steps to workflow top level
  .github/workflows/lint-test.yml
Labels: p: medium, s: needs review, t: meta, skip news

#936 deps: update sphinx to 6.0.1
  changelog/936.misc.rst
  changelog/_template.rst.jinja
  docs/_templates/layout.html
  requirements/requirements_docs.txt
  requirements/requirements_tools.txt
Labels: t: documentation, s: needs review, t: dependencies

#938 ci: allow usage of merge queues #933
  .github/workflows/lint-test.yml
Labels: s: needs review, t: meta, skip news

#941 docs: update path to favicon after sphinx 6.0.1 update
  docs/_templates/layout.html
Labels: t: documentation, s: needs review, skip news

#929 feat: add `MessageFlags.suppress_notifications` and `flags` parameter
  changelog/929.feature.0.rst
  changelog/929.feature.1.rst
  disnake/abc.py
  disnake/channel.py
  disnake/flags.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement, t: api support, s: needs review

#919 feat: add `oldest_first` parameter to `Guild.audit_logs`
  changelog/919.feature.rst
  disnake/guild.py
  disnake/http.py
  disnake/iterators.py
Labels: t: enhancement, t: api support, s: needs review

#904 feat: implement role subscription fields
  changelog/904.feature.rst
  disnake/emoji.py
  disnake/enums.py
  disnake/guild.py
  disnake/integrations.py
  disnake/message.py
  disnake/role.py
  disnake/types/guild.py
  disnake/types/integration.py
  disnake/types/message.py
  disnake/types/role.py
  docs/api.rst
Labels: t: enhancement, t: api support, s: needs review

#943 fix: logging being passed log calls within traceback
  changelog/940.bugfix.rst
  disnake/gateway.py
Labels: s: needs review, t: bugfix, needs backport: 2.8

#836 feat: use pdm for dependency management
  .github/actions/setup-env/action.yml
  .github/workflows/changelog.yaml
  .github/workflows/lint-test.yml
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  MANIFEST.in
  changelog/836.misc.rst
  noxfile.py
  pyproject.toml
  requirements.txt
  requirements/requirements_dev.txt
  requirements/requirements_docs.txt
  requirements/requirements_speed.txt
  requirements/requirements_tools.txt
  requirements/requirements_voice.txt
  setup.py
Labels: t: dependencies, t: meta

#935 feat(lint): switch to ruff
  .flake8
  .github/actions/setup-env/action.yml
  .github/workflows/lint-test.yml
  .pre-commit-config.yaml
  changelog/935.misc.rst
  disnake/enums.py
  disnake/ext/commands/bot_base.py
  disnake/ext/commands/flag_converter.py
  disnake/ext/commands/params.py
  disnake/ext/commands/view.py
  disnake/interactions/message.py
  disnake/member.py
  disnake/player.py
  disnake/utils.py
  docs/conf.py
  docs/extensions/attributetable.py
  docs/extensions/builder.py
  docs/extensions/exception_hierarchy.py
  docs/extensions/nitpick_file_ignorer.py
  docs/extensions/resourcelinks.py
  examples/background_task.py
  examples/converters.py
  noxfile.py
  pyproject.toml
  setup.py
  test_bot/__main__.py
  tests/helpers.py
  tests/interactions/test_base.py
  tests/test_abc.py
  tests/test_embeds.py
Labels: s: needs review, t: meta, t: refactor/typing/lint

#952 fix: update excess taskipy references/installation
  .github/PULL_REQUEST_TEMPLATE.md
  pyproject.toml
Labels: s: needs review, t: meta, skip news

#945 fix: Do not duplicate event entries when searching.
  changelog/944.doc.rst
  disnake/ext/commands/base_core.py
  disnake/ext/commands/bot.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/errors.py
  disnake/ext/commands/flag_converter.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/params.py
  docs/ext/commands/api.rst
Labels: t: documentation, s: needs review

#953 chore(contrib): install nox into the local development environment rather than global
  CONTRIBUTING.md
  changelog/953.misc.rst
  changelog/README.rst
  noxfile.py
  pyproject.toml
Labels: t: documentation, t: dependencies, t: meta

#949 refactor(lint): add pylint rules
  disnake/opus.py
  pyproject.toml
Labels: s: needs review, t: meta, skip news

#955 lint: enable datetime rules
  changelog/945.bugfix.rst
  disnake/member.py
  disnake/raw_models.py
  pyproject.toml
  tests/test_embeds.py
  tests/test_utils.py
Labels: s: needs review, t: refactor/typing/lint, t: bugfix, skip news

#954 feat(AutoMod): add support for custom_message
  changelog/954.feature.rst
  disnake/automod.py
  disnake/types/automod.py
Labels: t: enhancement, t: api support, s: needs review

#942 feat: text in stage
  changelog/942.bugfix.0.rst
  changelog/942.feature.0.rst
  changelog/942.feature.1.rst
  changelog/942.feature.2.rst
  changelog/942.feature.3.rst
  disnake/abc.py
  disnake/channel.py
  disnake/enums.py
  disnake/ext/commands/core.py
  disnake/guild.py
  disnake/interactions/base.py
  disnake/message.py
  disnake/state.py
  disnake/webhook/async_.py
  docs/api.rst
Labels: t: enhancement, t: api support, s: needs review

#960 fix: prevent an attribute error when accessing channel.flags in DMChannels under certain conditions
  changelog/960.bugfix.rst
  disnake/channel.py
Labels: s: needs review, t: bugfix, needs backport: 2.8

#962 feat: add `VoiceRegion.__eq__`
  changelog/962.feature.rst
  disnake/voice_region.py
Labels: t: enhancement, s: needs review

#964 fix(typing): install pytz for type-checking examples
  pyproject.toml
Labels: p: high, s: needs review, t: dependencies, t: meta, skip news
