Repository DisnakeDev/disnake, pull requests merged in 2024-02, with the labels that each got.

#1137 docs: misc fixes/clarifications
  changelog/1045.bugfix.rst
  changelog/1111.bugfix.rst
  disnake/abc.py
  disnake/ext/commands/common_bot_base.py
  disnake/threads.py
  disnake/ui/select/role.py
Labels: t: documentation, skip news

#1135 build(meta): add Python 3.12 package classifier
  .github/workflows/lint-test.yml
  changelog/1117.feature.rst
  changelog/1128.feature.0.rst
  changelog/1128.feature.1.rst
  changelog/1135.feature.rst
  pyproject.toml
Labels: t: documentation, t: meta

#1050 feat: support media channels
  changelog/1050.feature.rst
  disnake/abc.py
  disnake/audit_logs.py
  disnake/channel.py
  disnake/context_managers.py
  disnake/enums.py
  disnake/ext/commands/converter.py
  disnake/flags.py
  disnake/guild.py
  disnake/message.py
  disnake/permissions.py
  disnake/state.py
  disnake/threads.py
  disnake/types/channel.py
  disnake/webhook/async_.py
  disnake/webhook/sync.py
  docs/api/audit_logs.rst
  docs/api/channels.rst
  docs/api/events.rst
  docs/ext/commands/api/converters.rst
  docs/ext/commands/commands.rst
Labels: t: enhancement, t: api support, s: needs review

#1154 feat: Add raw equivalent of `on_presence_update` - `on_raw_presence_update`.
  changelog/1152.feature.rst
  disnake/enums.py
  disnake/flags.py
  disnake/raw_models.py
  disnake/state.py
  docs/api/activities.rst
  docs/api/events.rst
  docs/api/members.rst
Labels: t: enhancement, s: needs review

#1157 docs: update supported image formats for bot avatars
  disnake/user.py
Labels: t: documentation, t: api support, skip news

#1158 docs: add clarification to executable param
  changelog/1158.doc.rst
  disnake/player.py
Labels: t: documentation
