Repository DisnakeDev/disnake, pull requests merged in 2024-09, with the labels that each got.

#1234 fix(changelog): fix poll changelog
  changelog/1175.feature.rst
Labels: t: documentation, skip news

#1207 docs: update build for new readthedocs addons
  docs/_static/style.css
  docs/_templates/layout.html
  docs/conf.py
Labels: t: documentation, s: in progress, skip news, needs backport: 2.9

#1233 feat: deserialize dm/group channels in interactions
  changelog/1233.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/ext/commands/context.py
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/message.py
  disnake/state.py
  disnake/ui/select/channel.py
  tests/interactions/test_base.py
Labels: t: enhancement
