Repository DisnakeDev/disnake, pull requests merged in 2024-11, with the labels that each got.

#1228 feat(voice): add `aead_xchacha20_poly1305_rtpsize` encryption mode, remove old modes
  changelog/1228.feature.rst
  changelog/1228.misc.rst
  disnake/gateway.py
  disnake/types/voice.py
  disnake/voice_client.py
  pyproject.toml
Labels: t: enhancement, t: api support, needs backport: 2.9

#1115 feat: select menu default values
  changelog/1115.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/components.py
  disnake/enums.py
  disnake/types/components.py
  disnake/types/interactions.py
  disnake/types/message.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/item.py
  disnake/ui/select/base.py
  disnake/ui/select/channel.py
  disnake/ui/select/mentionable.py
  disnake/ui/select/role.py
  disnake/ui/select/string.py
  disnake/ui/select/user.py
  docs/api/components.rst
  docs/api/ui.rst
  tests/ui/test_select.py
Labels: t: enhancement, t: api support, s: needs review

#1241 fix: attempt resume on websocket closure with `close_code = 1000` in edge cases
  changelog/1241.bugfix.rst
  disnake/gateway.py
Labels: t: bugfix, needs backport: 2.9

#1240 docs: Add parameter info to disnake.ext.commands.Bot.run() docstring
  disnake/client.py
Labels: t: documentation, s: needs review, skip news

#1229 feat(embed): add the ability to pass disnake.File to more Embed methods
  changelog/1184.feature.rst
  disnake/embeds.py
Labels: t: enhancement, s: needs review

#1204 feat(member): implement member banners
  changelog/1203.feature.rst
  disnake/asset.py
  disnake/member.py
  disnake/types/gateway.py
Labels: t: enhancement, t: api support

#1213 feat: add new poll system message type
  changelog/1212.feature.rst
  disnake/enums.py
  disnake/message.py
  disnake/types/embed.py
  disnake/types/message.py
  docs/api/messages.rst
Labels: t: enhancement, t: api support

#1248 feat(guild): implement new fetch role endpoint
  changelog/1247.feature.rst
  disnake/guild.py
  disnake/http.py
Labels: t: enhancement, t: api support, s: needs review

#1244 build(deps): update ruff to v0.8.0
  .pre-commit-config.yaml
  disnake/app_commands.py
  disnake/ext/commands/converter.py
  disnake/ext/commands/params.py
  disnake/ext/tasks/__init__.py
  disnake/interactions/base.py
  disnake/state.py
  disnake/utils.py
  pyproject.toml
  tests/ext/commands/test_params.py
Labels: t: dependencies, skip news

#1246 feat(flags): implement new member flags
  changelog/1245.feature.rst
  disnake/flags.py
Labels: t: enhancement, t: api support, s: needs review

#1252 fix: remove decorator check in `InvokableUserCommand`
  changelog/1252.bugfix.rst
  disnake/ext/commands/ctx_menus_core.py
  tests/ext/commands/test_base_core.py
Labels: p: low, t: bugfix

#1217 feat(member): implement new voice states endpoints
  changelog/1216.feature.rst
  disnake/guild.py
  disnake/http.py
Labels: t: enhancement, t: api support, s: needs review

#1238 feat: implement `__eq__` between BaseFlags and flag_values
  changelog/1238.feature.rst
  disnake/flags.py
  tests/test_flags.py
Labels: t: enhancement

#1200 fix(bug): `BucketType.role` in cooldowns could be based on a `Thread` rather than `Role`
  changelog/1200.bugfix.rst
  disnake/ext/commands/cooldowns.py
Labels: t: bugfix
