Repository DisnakeDev/disnake, pull requests merged in 2024-01, with the labels that each got.

#1085 feat(webhook): add `applied_tags` parameter
  changelog/1085.feature.rst
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement, t: api support, s: needs review

#1113 feat: application subscriptions
  changelog/1113.feature.rst
  disnake/__init__.py
  disnake/client.py
  disnake/entitlement.py
  disnake/enums.py
  disnake/flags.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/sku.py
  disnake/state.py
  disnake/types/entitlement.py
  disnake/types/gateway.py
  disnake/types/interactions.py
  disnake/types/sku.py
  docs/api/entitlements.rst
  docs/api/events.rst
  docs/api/index.rst
  docs/api/interactions.rst
  docs/api/skus.rst
Labels: t: enhancement, t: api support

#1143 ci: skip unnecessary release workflow run
  .github/workflows/lint-test.yml
  .github/workflows/release.yaml
Labels: t: meta, skip news

#1151 refactor(client): Add overloads for application command create and edit methods.
  changelog/1151.feature.rst
  disnake/client.py
Labels: t: enhancement, s: needs review, t: refactor/typing/lint

#1077 feat(webhook): improve thread support for webhook messages
  changelog/1077.feature.rst
  disnake/webhook/async_.py
  disnake/webhook/sync.py
Labels: t: enhancement, t: api support, s: needs review

#1155 fix(shard): handle `RECONNECT` opcode during initial connection flow
  changelog/1155.bugfix.rst
  disnake/shard.py
Labels: t: bugfix, needs backport: 2.9
