Repository DisnakeDev/disnake, pull requests merged in 2024-08, with the labels that each got.

#1214 fix(types.message): add missing system message types
  disnake/types/message.py
Labels: s: needs review, t: refactor/typing/lint, skip news

#1210 docs: update received fields for `Client.fetch_guilds`
  disnake/client.py
Labels: t: documentation, skip news

#1211 feat(permissions): add `use_external_apps` permission
  changelog/1211.feature.rst
  disnake/abc.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/permissions.py
Labels: t: enhancement, t: api support

#1142 feat: add `Invite.type`
  changelog/1142.bugfix.rst
  changelog/1142.feature.rst
  disnake/audit_logs.py
  disnake/enums.py
  disnake/guild.py
  disnake/invite.py
  disnake/types/gateway.py
  disnake/types/invite.py
  docs/api/invites.rst
Labels: t: enhancement, t: api support

#1215 docs(channel): clarify `ForumChannel.create_thread` return type
  disnake/channel.py
  docs/api/channels.rst
  docs/api/guilds.rst
Labels: t: documentation, skip news

#1222 feat(client): implement new sticker pack endpoint
  changelog/1221.feature.rst
  disnake/client.py
  disnake/http.py
Labels: t: enhancement, t: api support, s: needs review

#1227 fix: clarify AuditLogAction.overwrite_create
  changelog/1180.doc.rst
  docs/api/audit_logs.rst
Labels: t: documentation

#1231 docs: fix `Intents.*_typing` description
  disnake/flags.py
Labels: t: documentation, skip news

#1220 feat(app): add guild/user install count fields
  changelog/1220.feature.rst
  disnake/appinfo.py
  disnake/types/appinfo.py
Labels: t: enhancement, t: api support

#1219 feat(message): add Attachment.title
  changelog/1218.feature.rst
  disnake/message.py
  disnake/types/message.py
Labels: t: enhancement, t: api support, s: needs review

#1176 feat(polls): implement Polls
  changelog/1175.feature.rst
  disnake/__init__.py
  disnake/abc.py
  disnake/enums.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/flags.py
  disnake/http.py
  disnake/interactions/base.py
  disnake/iterators.py
  disnake/message.py
  disnake/permissions.py
  disnake/poll.py
  disnake/raw_models.py
  disnake/state.py
  disnake/threads.py
  disnake/types/gateway.py
  disnake/types/message.py
  disnake/types/poll.py
  disnake/webhook/async_.py
  docs/api/events.rst
  docs/api/messages.rst
  docs/intents.rst
Labels: t: enhancement, t: api support

#1012 feat(interactions): deserialize `channel` from data
  changelog/1012.feature.rst
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/state.py
  disnake/types/interactions.py
  tests/interactions/test_base.py
Labels: t: enhancement, t: api support, s: needs review

#1160 feat(message): include member data in `InteractionReference.user`
  changelog/1160.feature.rst
  disnake/message.py
  disnake/state.py
  disnake/types/interactions.py
Labels: t: enhancement, t: api support, p: low

#1232 fix(cog): fix typing of cog check methods
  disnake/ext/commands/cog.py
Labels: t: refactor/typing/lint, t: bugfix, skip news
