Repository DisnakeDev/disnake, pull requests merged in 2024-03, with the labels that each got.

#1166 fix: Examples Hyperlink Fix
  README.md
Labels: t: documentation, t: bugfix, skip news

#1163 fix(typing): support `Object` category in `create_x_channel`
  changelog/1050.feature.rst
  changelog/1162.bugfix.rst
  disnake/guild.py
Labels: p: low, t: refactor/typing/lint, t: bugfix

#1164 fix: handle missing `FFmpegAudio._process` in cleanup
  changelog/1164.bugfix.rst
  disnake/player.py
Labels: t: bugfix

#1171 fix(docs): add `entitlements` to interaction subclasses
  disnake/interactions/application_command.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
Labels: t: documentation, skip news

#1161 docs: update required permissions for prune
  disnake/guild.py
Labels: t: documentation, skip news

#1167 fix(typing): Reduce number of `Unknown`s in public APIs.
  changelog/1167.misc.rst
  disnake/abc.py
  disnake/channel.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/ctx_menus_core.py
  disnake/ext/commands/interaction_bot_base.py
  disnake/ext/commands/slash_core.py
  disnake/http.py
  disnake/message.py
Labels: s: needs review, t: refactor/typing/lint

#1159 fix(gateway): reconnect on protocol errors
  changelog/1159.bugfix.rst
  disnake/gateway.py
Labels: t: bugfix

#1179 fix(ci): adjust automatic release PR title to match commit format
  .github/workflows/create-release-pr.yaml
  .github/workflows/semantic-pr-title.yml
Labels: t: meta, t: bugfix, skip news

#1178 ci: update actions to avoid node version warnings
  .github/actions/setup-env/action.yml
  .github/workflows/changelog.yaml
  .github/workflows/create-release-pr.yaml
  .github/workflows/lint-test.yml
  .github/workflows/release.yaml
  .github/workflows/semantic-pr-title.yml
Labels: t: dependencies, t: meta, skip news

#1168 refactor(tools): Switch to ruff for import sorting.
  .pre-commit-config.yaml
  CONTRIBUTING.md
  examples/.ruff.toml
  pyproject.toml
Labels: s: needs review, t: meta, t: refactor/typing/lint, skip news
