Repository DisnakeDev/disnake, pull requests merged in 2025-09, with the labels that each got.

#1314 feat(permissions): add the new pin messages permission
  changelog/1313.feature.rst
  disnake/abc.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/core.py
  disnake/permissions.py
Labels: t: enhancement, t: api support, s: needs review

#1340 fix: change `Option.from_dict` to return cls instance instead of specifically `Option`
  disnake/app_commands.py
Labels: t: bugfix, skip news

#1306 feat: update the message pin endpoints
  changelog/1305.deprecate.rst
  changelog/1305.feature.rst
  disnake/abc.py
  disnake/http.py
  disnake/iterators.py
  disnake/message.py
  disnake/permissions.py
  disnake/types/channel.py
  disnake/types/message.py
Labels: t: api support, s: needs review, t: deprecation

#1339 chore: remove the test bot
  .gitignore
  noxfile.py
  pyproject.toml
  test_bot/__init__.py
  test_bot/__main__.py
  test_bot/cogs/events.py
  test_bot/cogs/guild_scheduled_events.py
  test_bot/cogs/injections.py
  test_bot/cogs/localization.py
  test_bot/cogs/message_commands.py
  test_bot/cogs/misc.py
  test_bot/cogs/modals.py
  test_bot/cogs/slash_commands.py
  test_bot/cogs/user_commands.py
  test_bot/config.py
  test_bot/example.env
  test_bot/locale/de.json
Labels: t: meta, skip news

#1342 fix(dev): enable typechecking on scripts
  pyproject.toml
  scripts/codemods/typed_permissions.py
Labels: t: refactor/typing/lint, skip news

#1347 chore(docs): miscellaneous changelog fixes
  changelog/1269.feature.rst
  changelog/1276.deprecate.rst
  changelog/1296.deprecate.rst
  changelog/1304.misc.rst
  changelog/1313.feature.rst
  changelog/1333.feature.rst
Labels: t: documentation, skip news

#1354 ci: enable ruff output formatting for pre-commit
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#1336 feat(ci): add libcst diff as a check summary to GH actions
  .github/workflows/lint-test.yml
Labels: skip news

#1357 fix(ci): stop vscode from complaining about invalid syntax
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#1352 fix(ci): require lint for all jobs
  .github/workflows/lint-test.yml
Labels: t: meta, skip news

#1358 fix: bump versions of hooks for pre-commit
  .pre-commit-config.yaml
  pyproject.toml
Labels: t: dependencies, t: meta, skip news

#1350 fix(gateway): fix missing `user_update` event for new attributes, missing attributes in `member_update` event
  changelog/1350.bugfix.rst
  disnake/member.py
  disnake/types/user.py
  disnake/user.py
Labels: t: bugfix

#1356 feat(packaging): migrate packages out of setup.py
  changelog/1356.misc.rst
  pyproject.toml
  setup.py
Labels: t: meta

#1321 feat: new modal components
  changelog/1321.deprecate.rst
  changelog/1321.feature.rst
  disnake/components.py
  disnake/enums.py
  disnake/interactions/base.py
  disnake/interactions/modal.py
  disnake/types/components.py
  disnake/types/interactions.py
  disnake/ui/__init__.py
  disnake/ui/_types.py
  disnake/ui/action_row.py
  disnake/ui/item.py
  disnake/ui/label.py
  disnake/ui/modal.py
  disnake/ui/section.py
  disnake/ui/select/base.py
  disnake/ui/select/channel.py
  disnake/ui/select/mentionable.py
  disnake/ui/select/role.py
  disnake/ui/select/string.py
  disnake/ui/select/user.py
  disnake/ui/text_input.py
  docs/api/components.rst
  docs/api/ui.rst
  docs/conf.py
  examples/interactions/modal.py
  tests/ui/test_action_row.py
  tests/ui/test_components.py
Labels: t: enhancement, t: api support, t: deprecation

#1312 feat: implement new color styles
  changelog/1311.feature.rst
  disnake/colour.py
  disnake/guild.py
  disnake/http.py
  disnake/role.py
  disnake/types/role.py
Labels: t: enhancement, t: api support, s: needs review

#1370 feat: add `emoji_added` message type
  changelog/1370.feature.rst
  disnake/enums.py
  disnake/flags.py
  disnake/message.py
Labels: t: enhancement, s: needs review

#1351 refactor(dev): rewrite setup_env to a nox session, deprecate pdm task running
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  changelog/README.rst
  noxfile.py
  pyproject.toml
Labels: t: meta, skip news

#1335 refactor(dev): write ruff lint config to be opt out rather than opt in
  disnake/asset.py
  disnake/audit_logs.py
  disnake/bans.py
  disnake/ext/commands/core.py
  disnake/i18n.py
  disnake/message.py
  disnake/shard.py
  disnake/ui/action_row.py
  disnake/ui/item.py
  disnake/utils.py
  docs/extensions/attributetable.py
  pyproject.toml
  scripts/codemods/base.py
  tests/test_utils.py
Labels: s: needs review, t: meta, t: refactor/typing/lint, skip news

#1224 feat(emoji)!: implement app emojis
  changelog/1223.breaking.rst
  changelog/1223.feature.rst
  disnake/client.py
  disnake/emoji.py
  disnake/http.py
  disnake/types/emoji.py
Labels: t: enhancement, t: api support, s: in progress

#1341 ci: run ci with specific environment definitions
  .github/actions/setup-env/action.yml
  .github/workflows/lint-test.yml
  noxfile.py
  pyproject.toml
Labels: t: meta, skip news

#1274 fix(sku)!: change `SKU.subscriptions` to be a sync method
  changelog/1274.breaking.rst
  changelog/1274.bugfix.rst
  disnake/sku.py
Labels: breaking change, t: bugfix

#1387 fix: re-enable reportInvalidTypeForm
  disnake/enums.py
  disnake/ext/commands/params.py
  pyproject.toml
Labels: t: refactor/typing/lint, skip news

#1380 feat(dev): use prek instead of pre-commit
  .github/workflows/lint-test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  noxfile.py
  pyproject.toml
Labels: s: needs review, t: meta, skip news

#1406 fix: re-enable other TC rules
  pyproject.toml
Labels: t: meta, skip news

#1403 ci: add dependabot to update github actions
  .github/dependabot.yaml
Labels: skip news

#1402 ci: pin all commit hashes and add zizmor security fixes
  .github/actions/setup-env/action.yml
  .github/workflows/changelog.yaml
  .github/workflows/check-pull-labels.yaml
  .github/workflows/create-release-pr.yaml
  .github/workflows/lint-test.yml
  .github/workflows/release.yaml
  .github/workflows/semantic-pr-title.yml
Labels: s: needs review, t: meta, skip news
