Repository DisnakeDev/disnake, pull requests merged in 2025-08, with the labels that each got.

#1287 fix(channel): improve handling of placeholder guilds in `GuildChannel` and `Thread`
  changelog/1287.bugfix.rst
  disnake/abc.py
  disnake/channel.py
  disnake/threads.py
Labels: p: low, t: bugfix, needs backport: 2.10

#828 refactor(typing): add annotations to `ext.commands.help`
  changelog/828.misc.rst
  disnake/ext/commands/_types.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/help.py
  disnake/ext/commands/params.py
Labels: s: needs review, t: refactor/typing/lint

#1294 feat: components v2
  changelog/1294.feature.rst
  disnake/abc.py
  disnake/channel.py
  disnake/components.py
  disnake/enums.py
  disnake/flags.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/message.py
  disnake/types/components.py
  disnake/types/interactions.py
  disnake/types/message.py
  disnake/ui/__init__.py
  disnake/ui/_types.py
  disnake/ui/action_row.py
  disnake/ui/button.py
  disnake/ui/container.py
  disnake/ui/file.py
  disnake/ui/item.py
  disnake/ui/media_gallery.py
  disnake/ui/modal.py
  disnake/ui/section.py
  disnake/ui/select/base.py
  disnake/ui/select/channel.py
  disnake/ui/select/mentionable.py
  disnake/ui/select/role.py
  disnake/ui/select/string.py
  disnake/ui/select/user.py
  disnake/ui/separator.py
  disnake/ui/text_display.py
  disnake/ui/text_input.py
  disnake/ui/thumbnail.py
  disnake/ui/view.py
  disnake/utils.py
  disnake/webhook/async_.py
  docs/api/components.rst
  docs/api/ui.rst
  docs/conf.py
  examples/components_v2.py
  tests/ui/test_action_row.py
  tests/ui/test_components.py
Labels: t: api support, s: needs review

#1304 docs: remove bad code snippet that can cause bugs
  changelog/1304.misc.rst
  examples/basic_voice.py
Labels: t: documentation, t: bugfix

#1319 feat(interactions): add `attachment_size_limit`
  changelog/1319.feature.rst
  disnake/interactions/application_command.py
  disnake/interactions/base.py
  disnake/interactions/message.py
  disnake/interactions/modal.py
  disnake/types/interactions.py
Labels: t: enhancement, t: api support

#1324 fix: use ClientWSTimeout for timeout to WS
  changelog/1324.bugfix.rst
  disnake/http.py
Labels: t: bugfix

#1326 chore: bump ruff
  .pre-commit-config.yaml
  changelog/1326.misc.rst
  disnake/abc.py
  disnake/components.py
  disnake/ext/commands/base_core.py
  disnake/ext/commands/cog.py
  disnake/ext/commands/core.py
  disnake/ext/commands/flag_converter.py
  disnake/interactions/base.py
  docs/extensions/fulltoc.py
  pyproject.toml
  tests/ext/commands/test_params.py
  tests/test_abc.py
  tests/test_utils.py
Labels: t: dependencies
